--
-- PostgreSQL database dump
--

\restrict Bctk5BQwexLgV0IxNrU8wadAgRQnrUUF9QQTkzmAC6DJ0P6RRTYlss0Qdfh7Pgm

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO memorial;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO memorial;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO memorial;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO memorial;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO memorial;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO memorial;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: biography_biography; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.biography_biography (
    id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    birth_date date,
    death_date date,
    portrait character varying(100),
    summary text NOT NULL,
    full_text text NOT NULL,
    award_title character varying(255) NOT NULL,
    intro_text text NOT NULL,
    rank character varying(255) NOT NULL,
    signature_quote character varying(500) NOT NULL
);


ALTER TABLE public.biography_biography OWNER TO memorial;

--
-- Name: biography_biography_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.biography_biography ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.biography_biography_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: biography_timelineevent; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.biography_timelineevent (
    id bigint NOT NULL,
    date_label character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(500) NOT NULL,
    "order" integer NOT NULL,
    biography_id bigint NOT NULL,
    CONSTRAINT biography_timelineevent_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.biography_timelineevent OWNER TO memorial;

--
-- Name: biography_timelineevent_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.biography_timelineevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.biography_timelineevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_sitesettings; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.core_sitesettings (
    id bigint NOT NULL,
    site_name character varying(100) NOT NULL,
    subtitle character varying(200) NOT NULL,
    brand_letter character varying(4) NOT NULL,
    footer_text text NOT NULL,
    copyright_holder character varying(200) NOT NULL,
    demo_strip_enabled boolean NOT NULL,
    site_title character varying(200) NOT NULL,
    memories_title character varying(100) NOT NULL,
    home_title character varying(100) NOT NULL,
    life_title character varying(100) NOT NULL,
    media_title character varying(100) NOT NULL,
    photos_title character varying(100) NOT NULL,
    service_title character varying(100) NOT NULL,
    videos_title character varying(100) NOT NULL,
    home_empty_text text NOT NULL,
    home_empty_title character varying(200) NOT NULL,
    home_gallery_empty_text character varying(200) NOT NULL,
    home_gallery_eyebrow character varying(100) NOT NULL,
    home_gallery_title character varying(200) NOT NULL,
    home_hero_eyebrow character varying(100) NOT NULL,
    home_life_description text NOT NULL,
    home_life_empty_text character varying(200) NOT NULL,
    home_life_eyebrow character varying(100) NOT NULL,
    home_life_title character varying(200) NOT NULL,
    home_media_description text NOT NULL,
    home_media_eyebrow character varying(100) NOT NULL,
    home_media_title character varying(200) NOT NULL,
    home_video_description text NOT NULL,
    home_video_title character varying(200) NOT NULL,
    life_empty_biography_text text NOT NULL,
    life_empty_page_text text NOT NULL,
    life_hero_description text NOT NULL,
    life_hero_eyebrow character varying(100) NOT NULL,
    life_photos_eyebrow character varying(100) NOT NULL,
    life_photos_title character varying(200) NOT NULL,
    life_timeline_description text NOT NULL,
    life_timeline_empty_text text NOT NULL,
    life_timeline_empty_title character varying(200) NOT NULL,
    life_timeline_eyebrow character varying(100) NOT NULL,
    life_timeline_title character varying(200) NOT NULL,
    service_award_title character varying(200) NOT NULL,
    service_checklist_eyebrow character varying(100) NOT NULL,
    service_checklist_item_1 character varying(300) NOT NULL,
    service_checklist_item_2 character varying(300) NOT NULL,
    service_checklist_item_3 character varying(300) NOT NULL,
    service_checklist_item_4 character varying(300) NOT NULL,
    service_checklist_title character varying(200) NOT NULL,
    service_decree_link_text character varying(200) NOT NULL,
    service_editorial_label character varying(150) NOT NULL,
    service_empty_text text NOT NULL,
    service_safety_eyebrow character varying(100) NOT NULL,
    service_section_title character varying(200) NOT NULL,
    photos_category_empty_text character varying(250) NOT NULL,
    photos_empty_text text NOT NULL,
    photos_empty_title character varying(200) NOT NULL,
    photos_hero_description text NOT NULL,
    photos_hero_title character varying(200) NOT NULL,
    photos_verification_note text NOT NULL,
    videos_accessibility_label character varying(100) NOT NULL,
    videos_accessibility_text text NOT NULL,
    videos_admin_note text NOT NULL,
    videos_all_records_label character varying(100) NOT NULL,
    videos_archive_title character varying(200) NOT NULL,
    videos_empty_text text NOT NULL,
    videos_empty_title character varying(200) NOT NULL,
    videos_featured_label character varying(150) NOT NULL,
    videos_hero_description text NOT NULL,
    videos_hero_eyebrow character varying(100) NOT NULL,
    videos_transcript_label character varying(150) NOT NULL,
    media_empty_text text NOT NULL,
    media_empty_title character varying(200) NOT NULL,
    media_hero_description text NOT NULL,
    media_hero_eyebrow character varying(100) NOT NULL,
    media_section_title character varying(200) NOT NULL,
    media_verification_note text NOT NULL,
    memories_empty_text text NOT NULL,
    memories_empty_title character varying(200) NOT NULL,
    memories_hero_description text NOT NULL,
    memories_hero_eyebrow character varying(100) NOT NULL,
    memories_moderation_label character varying(100) NOT NULL,
    memories_moderation_note text NOT NULL,
    memories_moderator_text character varying(200) NOT NULL,
    memories_submit_description text NOT NULL,
    memories_submit_eyebrow character varying(100) NOT NULL,
    memories_submit_title character varying(200) NOT NULL
);


ALTER TABLE public.core_sitesettings OWNER TO memorial;

--
-- Name: core_sitesettings_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.core_sitesettings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_sitesettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO memorial;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO memorial;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO memorial;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO memorial;

--
-- Name: gallery_photo; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.gallery_photo (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    caption character varying(255) NOT NULL,
    layout_size character varying(20) NOT NULL,
    "order" integer NOT NULL,
    alt_text character varying(255) NOT NULL,
    category character varying(20) NOT NULL,
    is_published boolean NOT NULL,
    CONSTRAINT gallery_photo_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.gallery_photo OWNER TO memorial;

--
-- Name: gallery_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.gallery_photo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_mentions_mediamention; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.media_mentions_mediamention (
    id bigint NOT NULL,
    source_name character varying(255) NOT NULL,
    url character varying(200) NOT NULL,
    published_date date,
    "order" integer NOT NULL,
    category character varying(20) NOT NULL,
    is_published boolean NOT NULL,
    title character varying(255) NOT NULL,
    is_featured boolean NOT NULL,
    CONSTRAINT media_mentions_mediamention_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.media_mentions_mediamention OWNER TO memorial;

--
-- Name: media_mentions_mediamention_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.media_mentions_mediamention ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_mentions_mediamention_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memories_memory; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.memories_memory (
    id bigint NOT NULL,
    author_name character varying(255) NOT NULL,
    author_role character varying(255) NOT NULL,
    text text NOT NULL,
    featured boolean NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.memories_memory OWNER TO memorial;

--
-- Name: memories_memory_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.memories_memory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memories_memory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pages_servicepage; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.pages_servicepage (
    id bigint NOT NULL,
    hero_eyebrow character varying(150) NOT NULL,
    hero_title character varying(150) NOT NULL,
    hero_description text NOT NULL,
    publication_status character varying(30) NOT NULL,
    service_intro text NOT NULL,
    service_text text NOT NULL,
    editorial_note text NOT NULL,
    award_title character varying(255) NOT NULL,
    award_subtitle character varying(255) NOT NULL,
    decree_date date,
    decree_number character varying(100) NOT NULL,
    decree_source_name character varying(255) NOT NULL,
    decree_url character varying(200) NOT NULL,
    is_published boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.pages_servicepage OWNER TO memorial;

--
-- Name: pages_servicepage_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.pages_servicepage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pages_servicepage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seo_seopage; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.seo_seopage (
    id bigint NOT NULL,
    page_key character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(320) NOT NULL,
    og_image character varying(100)
);


ALTER TABLE public.seo_seopage OWNER TO memorial;

--
-- Name: seo_seopage_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.seo_seopage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seo_seopage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: videos_video; Type: TABLE; Schema: public; Owner: memorial
--

CREATE TABLE public.videos_video (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    thumbnail character varying(100),
    "order" integer NOT NULL,
    category character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    description text NOT NULL,
    duration character varying(20) NOT NULL,
    is_featured boolean NOT NULL,
    is_published boolean NOT NULL,
    recorded_at character varying(100) NOT NULL,
    transcript text NOT NULL,
    video_file character varying(100) NOT NULL,
    CONSTRAINT videos_video_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.videos_video OWNER TO memorial;

--
-- Name: videos_video_id_seq; Type: SEQUENCE; Schema: public; Owner: memorial
--

ALTER TABLE public.videos_video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.videos_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Налаштування сайту	7	add_sitesettings
26	Can change Налаштування сайту	7	change_sitesettings
27	Can delete Налаштування сайту	7	delete_sitesettings
28	Can view Налаштування сайту	7	view_sitesettings
29	Can add Життєпис	8	add_biography
30	Can change Життєпис	8	change_biography
31	Can delete Життєпис	8	delete_biography
32	Can view Життєпис	8	view_biography
33	Can add Відео	9	add_video
34	Can change Відео	9	change_video
35	Can delete Відео	9	delete_video
36	Can view Відео	9	view_video
37	Can add Спогад	10	add_memory
38	Can change Спогад	10	change_memory
39	Can delete Спогад	10	delete_memory
40	Can view Спогад	10	view_memory
41	Can add Подія хронології	11	add_timelineevent
42	Can change Подія хронології	11	change_timelineevent
43	Can delete Подія хронології	11	delete_timelineevent
44	Can view Подія хронології	11	view_timelineevent
45	Can add Фото	12	add_photo
46	Can change Фото	12	change_photo
47	Can delete Фото	12	delete_photo
48	Can view Фото	12	view_photo
49	Can add Згадка в медіа	13	add_mediamention
50	Can change Згадка в медіа	13	change_mediamention
51	Can delete Згадка в медіа	13	delete_mediamention
52	Can view Згадка в медіа	13	view_mediamention
53	Can add SEO сторінки	14	add_seopage
54	Can change SEO сторінки	14	change_seopage
55	Can delete SEO сторінки	14	delete_seopage
56	Can view SEO сторінки	14	view_seopage
57	Can add Подвиг і служба	15	add_servicepage
58	Can change Подвиг і служба	15	change_servicepage
59	Can delete Подвиг і служба	15	delete_servicepage
60	Can view Подвиг і служба	15	view_servicepage
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1200000$Xt3RurR8ZQWeZt2SBOjYnO$oY+FW5p2Tym4ExIrd/VZWR7HzWOd7bRiPZctM8b5b3M=	2026-08-29 19:14:25.010227+00	t	admin			admin@except.com	t	t	2026-08-04 13:14:02.632762+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: biography_biography; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.biography_biography (id, full_name, birth_date, death_date, portrait, summary, full_text, award_title, intro_text, rank, signature_quote) FROM stdin;
1	Боровицький Назар Богданович	1993-09-24	2022-04-05	biography/IMG_5964.JPG	Роби все, що можеш там, де ти є, використовуючи все, що маєш.	Назар народився 24 вересня 1993 року в м. Полтава в сім’ї Богдана Володимировича та Лесі Олександрівни Боровицьких. Назар був другою дитиною в сім’ї. Першою була донечка Оксана, яка була гарною та надійною нянькою для братика, пильнувала та оберігала його. \r\n\r\nЗ самого раннього дитинства Назар гуртував біля себе друзів. Був ініціатором дитячих ігор. Дуже любив грати у футбол. Починаючи з 5-6 класу почав загартовувати себе фізично: підтягування на турніку не просто, а наклавши в рюкзак цегли, біг, віджимання від підлоги, качання пресу.\r\n\r\nНазар навчався в Пашківській загальноосвітній школі 1-3 ступенів з 2000 року по 2008 рік. Під час навчання в школі був активним учасником шкільних вистав, концертів, виховних заходів та спортивних змагань. Батькам ніколи не було соромно за поведінку свого сина. Він ріс чесним, відкритим, щирим, із загостреним відчуттям справедливості, яку завжди відстоював, де б він не був. Він був надійним плечем для друзів. \r\n\r\nЗ 2009 по 2011 рік навчався в ліцеї-інтернаті для обдарованої молоді при Кременчуцькому педагогічному училищі з поглибленим вивченням інформаційних технологій. Був старостою групи протягом трьох років. Навчався сумлінно та на відмінно. Закінчив 11 клас з золотою медаллю. “В здоровому тілі здоровий дух” \\- на перервах Назар любив грати у футбол, а також додатково відвідував спортивну секцію з боксу. \r\n\r\nУ 2011 році Назар вступає до Національної академії Служби безпеки України, пройшовши непростий, складний відбір. Упродовж чотирьох років був старшиною курсу. Із перших днів військової служби Назар зарекомендував себе сумлінним та дисциплінованим курсантом, який успішно опановував навчальну програму та відповідально ставився до виконання службових обов’язків. І саме за це неодноразово був нагороджений грамотами та дипломами Національною академією Служби безпеки України. Завдяки цілеспрямованій та наполегливій роботі Назара, умілому поєднанню ним вимогливості із всебічним піклуванням про підлеглих, курсантський колектив під його керівництвом став одним з кращих підрозділів Академії. Назар мав заслужений авторитет серед офіцерів і курсантів. \r\n\r\nПо закінченню четвертого курсу, у 2015 році, Назар приймає рішення достроково завершити навчання, стати в ряди захисників Батьківщини підписавши контракт з Головним управлінням Служби безпеки України.   \r\nНазар з групою курсантів-добровольців вирушає на навчання до США, де було багато практики не лише з військової справи, але й з надання першої медичної допомоги. Повернувшись з США, Назар разом зі своїми однокурсниками-добровольцями та старшими побратимами їдуть на схід захищати Батьківщину. Завдяки знанням здобутих в США та особистісним якостям: мужності, героїзму, рішучості та холодному розуму, Назар неодноразово рятував життя воїнам ЗСУ.  \r\n\r\n3 серпня 2019 року Назар взяв шлюб з Латер Анастасією. Настя для Назара була добрим, вірним та надійним другом і коханою.\r\n\r\nПід час ротацій Назар повертався до роботи в Києві, паралельно навчаючись та  удосконалюючи свою військову майстерність. Він отримав багато сертифікатів міжнародного зразка, опанувавши військові спеціальності водолаза, сапера, інструктора спецоперацій, здійснивши близько ста стрибків з парашутом різної складності, пройшовши курси “Спеціальних операцій з нагляду та розвідки”, “Підготовка розвідки для курсу бойової медицини”, “Надання першої допомоги у надзвичайних ситуаціях”.   \r\nНавесні 2021 року Назар підписує контракт з ГУР МО ЗСУ. Наприкінці серпня 2021 року Назар бере участь в рятувально-евакуаційній місії в Афганістані. Назар зі своїми побратимами ідуть туди, куди відмовляються іти військовослужбовці рятувальних, іноземних місій. Назар виносить на руках міжнародну журналістку, афганку Фатіму громадянства Канади, без страху отримати з будь-якого кутка кулю від Талібів.   \r\nУ грудні 2021 року Назар їде на схід України, де і зустрічає початок повномасштабного вторгнення рф. Як тільки стало зрозуміло, що Київ під загрозою, Назар на чолі групи їде боронити столицю, беручи участь в боях у Бородянці, Бучі та інших селах Київської області. Коли ворога було відкинуто від Києва, Назар зі своєю групою отримує наказ відправитись на маріупольський напрямок. І починаються звитяжні польоти на Азовсталь, коли Маріуполь вже був в облозі. Була домовленість серед пілотів та військових, які супроводжували польоти, летіти один раз. Але командир групи, капітан Назар Боровицький, здійснив три польоти. 5 квітня 2022 року рано вранці був отриманий сигнал SOS від вертольота з пораненими, який вилетів з Азовсталі. Спеціальна рятувально-пошукова група, яка мала виконувати цю роботу, відмовилась летіти, знаючи, що це може бути політ в один кінець. Назар зі своєю групою взяв відповідальність на себе, вилетівши втретє на допомогу. Орки вже чекали та підбили вертоліт. Чотири кілометри \\- поділ між  життям і смертю, бо саме стільки кілометрів не вистачило, щоб долетіти до лінії розмежування. Це був, насправді, героїчний вчинок. На місці катастрофи вертольотів була братська могила, де орки як-небудь присипали тіла наших героїв. Усі зусилля, які були докладені ГУР МО ЗСУ щодо ексгумації, завершувались відмовою ворога. Лише у травні 2023 року орки  передали останки тіл наших героїв.  \r\nРік і три місяці рідні та близькі вірили, надіялись, молились, що син, брат, чоловік, побратим, друг живий. На жаль, 17 липня була отримана страшна, чорна звістка про співпадіння ДНК на 99,9%. \r\n\r\nТи для нас завжди залишися промінчиком СВІТЛА, ЛЮБОВІ, РАДОСТІ та ЩАСТЯ, ОПТИМІЗМУ, ПОЗИТИВУ, ДОБРА, ЛЮДИНОЛЮБСТВА. ТИ ДУЖЕ СПІШИВ ДОПОМОГТИ ВСІМ І КОЖНОМУ, ОГОРНУТИ ВСІХ. ТИ БУВ СПРАВЖНІМ ДРУГОМ, ЯКИЙ НІКОЛИ НЕ ЗАЛИШИТЬ У БІДІ І ЗАВЖДИ ПОРАДІЄ В РАДОСТІ. ТОБІ НАЗАВЖДИ БУДЕ 28 З ПОЛОВИНОЮ\\!	Звання Герой України з  удостоєнням ордена «Золота Зірка»	Назар Боровицький — український військовослужбовець і офіцер спеціального призначення, який присвятив життя захисту України та порятунку людей. Він брав участь у бойових операціях на сході України, рятувально-евакуаційній місії в Афганістані, обороні Київщини та надскладних польотах до оточеного Маріуполя.	Майор Головного управління розвідки Міністерства оборони України	Never out of   the fight.
\.


--
-- Data for Name: biography_timelineevent; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.biography_timelineevent (id, date_label, title, description, "order", biography_id) FROM stdin;
1	2000–2008	Пашківська загальноосвітня школа I–III ступенів.	Назар народився 24 вересня 1993 року в м. Полтава в сім’ї Богдана Володимировича та Лесі Олександрівни Боровицьких. Назар був другою дитиною в сім’ї. Першою була донечка Оксана, яка була гарною та надійною нянькою для братика, пильнувала та оберігала його.   З самого раннього дитинства Назар гуртував біля себе друзів. Був ініціатором дитячих ігор. Дуже любив грати у футбол. Починаючи з 5-6 класу почав загартовувати себе фізично: підтягування на турніку не просто, а наклавши в рюкзак цегли, біг,	1	1
2	2008/2009–2011	Ліцей для обдарованої молоді при Кременчуцькому педагогічному училищі; поглиблене вивчення інформаційних технологій; староста; золота медаль.	З 2009 по 2011 рік навчався в ліцеї-інтернаті для обдарованої молоді при Кременчуцькому педагогічному училищі з поглибленим вивченням інформаційних технологій. Був старостою групи протягом трьох років. Навчався сумлінно та на відмінно. Закінчив 11 клас з золотою медаллю. “В здоровому тілі здоровий дух” \\- на перервах Назар любив грати у футбол, а також додатково відвідував спортивну секцію з боксу.	2	1
3	2011–2015	Національна академія СБУ; старшина курсу.	У 2011 році Назар вступає до Національної академії Служби безпеки України, пройшовши непростий, складний відбір. Упродовж чотирьох років був старшиною курсу. Із перших днів військової служби Назар зарекомендував себе сумлінним та дисциплінованим курсантом, який успішно опановував навчальну програму та відповідально ставився до виконання службових обов’язків. І саме за це неодноразово був нагороджений грамотами та дипломами Національною академією Служби безпеки України. Завдяки цілеспрямованій та	3	1
4	2015–2022	Служба, бойові ротації, підготовка за різними військовими спеціальностями.	По закінченню четвертого курсу, у 2015 році, Назар приймає рішення достроково завершити навчання, стати в ряди захисників Батьківщини підписавши контракт з Головним управлінням Служби безпеки України.    Назар з групою курсантів-добровольців вирушає на навчання до США, де було багато практики не лише з військової справи, але й з надання першої медичної допомоги. Повернувшись з США, Назар разом зі своїми однокурсниками-добровольцями та старшими побратимами їдуть на схід захищати Батьківщину. Завд	4	1
6	1993	Народився	Назар народився 24 вересня 1993 року в м. Полтава в сім’ї Богдана Володимировича та Лесі Олександрівни Боровицьких. Назар був другою дитиною в сім’ї. Першою була донечка Оксана, яка була гарною та надійною нянькою для братика, пильнувала та оберігала його.   З самого раннього дитинства Назар гуртував біля себе друзів. Був ініціатором дитячих ігор. Дуже любив грати у футбол. Починаючи з 5-6 класу почав загартовувати себе фізично: підтягування на турніку не просто, а наклавши в рюкзак цегли, біг,	0	1
\.


--
-- Data for Name: core_sitesettings; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.core_sitesettings (id, site_name, subtitle, brand_letter, footer_text, copyright_holder, demo_strip_enabled, site_title, memories_title, home_title, life_title, media_title, photos_title, service_title, videos_title, home_empty_text, home_empty_title, home_gallery_empty_text, home_gallery_eyebrow, home_gallery_title, home_hero_eyebrow, home_life_description, home_life_empty_text, home_life_eyebrow, home_life_title, home_media_description, home_media_eyebrow, home_media_title, home_video_description, home_video_title, life_empty_biography_text, life_empty_page_text, life_hero_description, life_hero_eyebrow, life_photos_eyebrow, life_photos_title, life_timeline_description, life_timeline_empty_text, life_timeline_empty_title, life_timeline_eyebrow, life_timeline_title, service_award_title, service_checklist_eyebrow, service_checklist_item_1, service_checklist_item_2, service_checklist_item_3, service_checklist_item_4, service_checklist_title, service_decree_link_text, service_editorial_label, service_empty_text, service_safety_eyebrow, service_section_title, photos_category_empty_text, photos_empty_text, photos_empty_title, photos_hero_description, photos_hero_title, photos_verification_note, videos_accessibility_label, videos_accessibility_text, videos_admin_note, videos_all_records_label, videos_archive_title, videos_empty_text, videos_empty_title, videos_featured_label, videos_hero_description, videos_hero_eyebrow, videos_transcript_label, media_empty_text, media_empty_title, media_hero_description, media_hero_eyebrow, media_section_title, media_verification_note, memories_empty_text, memories_empty_title, memories_hero_description, memories_hero_eyebrow, memories_moderation_label, memories_moderation_note, memories_moderator_text, memories_submit_description, memories_submit_eyebrow, memories_submit_title) FROM stdin;
1	Пам’ять про Назара	Borovitskyi Nazar Bogdanovych	NB	Цифровий простір пам’яті:  історія життя, фото, відео, публікації та слова близьких.	Родина Borovitskyi Nazar Bogdanovych	f	Nazar Borovytskyi	Спогади	Головна	Життя	Посилання	Фото	Подвиг і служба	Відео	Інформація ще готується до публікації.	Сторінка пам’яті	Фотоархів ще наповнюється	Фотоархів	Моменти життя	Світла пам’ять	Біографія, важливі дати та підтверджені родиною події — без вигаданих деталей і зайвої публічності.	Хронологію ще додають.	Його життя	Історія людини, яку пам’ятають	Добірка перевірених посилань на статті, новини та офіційні документи.	Публікації	Матеріали та офіційні джерела	Інтерв’ю, архівні записи та матеріали вшанування з короткими текстовими описами.	Голос і живі спогади	Повний життєпис ще готується до публікації.	Інформація для цієї сторінки ще готується.	Ознайомтесь з головними подіями з життя Назара	Про нього	Фото до історії	Роки, що залишилися у світлинах	До публікації додаються лише події з підтвердженими датами та формулюваннями.	Підтверджені події з’являться тут після додавання через адміністративну панель.	Хронологія ще наповнюється	Хронологія	Ключові події	Нагорода	Перед публікацією	Текст погоджено з частиною або пресслужбою.	Дата й номер Указу звірені з офіційним джерелом.	Немає координат, тактики, чисельності чи заборонених деталей.	Формулювання схвалені родиною.	Перевірка фактів і безпеки	Читати повний текст Указу	Редакційна позначка	Інформація для цього розділу ще не додана.	Безпека публікації	Опис служби1	У цій категорії поки немає фотографій.	Перевірені родиною фотографії з’являться тут після публікації.	Фотоархів ще наповнюється	Основний архів світлин, згрупований за періодами життя.	Фотоархів	Кожне фото публікується лише після перевірки.	Доступність:	за можливості до відео додається текстовий опис або розшифровка.	Усі матеріали додаються та публікуються тільки через адміністративну панель.	Усі записи	Відеоархів	Перевірені відеоматеріали з’являться тут після публікації адміністратором.	Відеоархів ще наповнюється	Рекомендоване відео	Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.	Архівні записи	Текстовий опис відео	Перевірені публікації та офіційні джерела з’являться тут пізніше.	Матеріалів поки немає	Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.	Зовнішні джерела	Матеріали	Перевірка посилань рекомендована 1–2 рази на рік.	Після перевірки модератором опубліковані спогади з’являться тут.	Спогадів поки немає	Слова родини, побратимів, друзів і однокласників.	Слова близьких	Модерація	Кожен текст публікується лише після ручної модерації.	Відповідальна особа від родини	Кожне повідомлення потрапляє на ручну модерацію й не з’являється на сайті автоматично.	Поділитися спогадом	Залиште кілька слів
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-04 13:17:24.065241+00	1	Alex: Test processa spogadiv	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u043d\\u0430 \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u0456\\u0439", "\\u0421\\u0442\\u0430\\u0442\\u0443\\u0441"]}}]	10	2
2	2026-08-04 13:18:06.06162+00	1	Alex: Test processa spogadiv	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u043d\\u0430 \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u0456\\u0439"]}}]	10	2
3	2026-08-04 13:47:39.757457+00	1	Боровицький Назар Богданович	1	[{"added": {}}]	8	2
4	2026-08-04 14:01:37.678858+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u0412\\u0441\\u0442\\u0443\\u043f\\u043d\\u0438\\u0439 \\u0442\\u0435\\u043a\\u0441\\u0442 \\u043d\\u0430 \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u0456\\u0439", "\\u041a\\u043b\\u044e\\u0447\\u043e\\u0432\\u0430 \\u0446\\u0438\\u0442\\u0430\\u0442\\u0430", "\\u041a\\u043e\\u0440\\u043e\\u0442\\u043a\\u0438\\u0439 \\u043e\\u043f\\u0438\\u0441 (\\u0434\\u043b\\u044f \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u043e\\u0457)", "\\u041f\\u043e\\u0432\\u043d\\u0438\\u0439 \\u0436\\u0438\\u0442\\u0442\\u0454\\u043f\\u0438\\u0441"]}}]	8	2
5	2026-08-04 14:05:26.041883+00	1	2000–2008 — Пашківська загальноосвітня школа I–III ступенів.	1	[{"added": {}}]	11	2
6	2026-08-04 14:06:23.635694+00	2	2008/2009–2011 — ліцей для обдарованої молоді при Кременчуцькому педагогічному училищі; поглиблене вивчення інформаційних технологій; староста; золота медаль.	1	[{"added": {}}]	11	2
7	2026-08-04 14:06:32.189916+00	2	2008/2009–2011 — Ліцей для обдарованої молоді при Кременчуцькому педагогічному училищі; поглиблене вивчення інформаційних технологій; староста; золота медаль.	2	[{"changed": {"fields": ["\\u0417\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u043f\\u043e\\u0434\\u0456\\u0457"]}}]	11	2
8	2026-08-04 14:07:15.357184+00	3	2011–2015 — Національна академія СБУ; старшина курсу.	1	[{"added": {}}]	11	2
9	2026-08-04 14:09:04.268309+00	4	2015–2022 — Служба, бойові ротації, підготовка за різними військовими спеціальностями.	1	[{"added": {}}]	11	2
10	2026-08-04 14:17:09.700288+00	1	Borovitskyi Nazar	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430 \\u0441\\u0430\\u0439\\u0442\\u0443", "\\u041b\\u0456\\u0442\\u0435\\u0440\\u0430 \\u043b\\u043e\\u0433\\u043e\\u0442\\u0438\\u043f\\u0430", "\\u041d\\u0430\\u0437\\u0432\\u0430 \\u0432 \\u0448\\u0430\\u043f\\u0446\\u0456", "\\u041f\\u0456\\u0434\\u0437\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u0443 \\u0448\\u0430\\u043f\\u0446\\u0456", "\\u041f\\u0440\\u0430\\u0432\\u043e\\u0432\\u043b\\u0430\\u0441\\u043d\\u0438\\u043a \\u0443 \\u043a\\u043e\\u043f\\u0456\\u0440\\u0430\\u0439\\u0442\\u0456"]}}]	7	2
11	2026-08-04 14:17:38.973721+00	1	Borovitskyi Nazar	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u0434\\u0435\\u043c\\u043e-\\u043f\\u043b\\u0430\\u0448\\u043a\\u0443"]}}]	7	2
12	2026-08-04 14:17:59.305777+00	1	Borovitskyi Nazar	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u0434\\u0435\\u043c\\u043e-\\u043f\\u043b\\u0430\\u0448\\u043a\\u0443"]}}]	7	2
13	2026-08-04 14:28:05.226358+00	1	Фото #1	1	[{"added": {}}]	12	2
14	2026-08-04 14:28:42.07795+00	2	Фото #2	1	[{"added": {}}]	12	2
15	2026-08-04 14:28:57.657513+00	3	Фото #3	1	[{"added": {}}]	12	2
16	2026-08-04 14:29:03.238466+00	3	Фото #3	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0443\\u0431\\u043b\\u0456\\u043a\\u043e\\u0432\\u0430\\u043d\\u043e"]}}]	12	2
17	2026-08-04 14:29:24.59673+00	4	Фото #4	1	[{"added": {}}]	12	2
18	2026-08-04 14:30:01.661497+00	3	Фото #3	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
19	2026-08-04 14:30:13.1899+00	4	Фото #4	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0443\\u0431\\u043b\\u0456\\u043a\\u043e\\u0432\\u0430\\u043d\\u043e"]}}]	12	2
20	2026-08-04 14:30:27.902445+00	2	Фото #2	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
21	2026-08-04 14:32:15.014113+00	5	Фото #5	1	[{"added": {}}]	12	2
22	2026-08-04 14:32:24.333939+00	5	Фото #5	3		12	2
23	2026-08-04 14:32:42.628464+00	6	Фото #6	1	[{"added": {}}]	12	2
24	2026-08-04 14:32:49.44378+00	6	Фото #6	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0443\\u0431\\u043b\\u0456\\u043a\\u043e\\u0432\\u0430\\u043d\\u043e"]}}]	12	2
25	2026-08-04 14:33:03.929918+00	2	Фото #2	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
26	2026-08-04 14:33:03.93107+00	6	Фото #6	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
27	2026-08-04 14:33:03.932004+00	1	Фото #1	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
28	2026-08-04 14:33:03.932841+00	4	Фото #4	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
29	2026-08-04 14:33:03.933666+00	3	Фото #3	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
30	2026-08-04 14:37:57.254105+00	2	Фото #2	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
31	2026-08-04 14:38:03.554914+00	6	Фото #6	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
32	2026-08-04 14:56:44.43728+00	1	1	1	[{"added": {}}]	9	2
33	2026-08-04 15:22:33.741565+00	2	Гречка: командирство, наставництво, підготовка д	1	[{"added": {}}]	10	2
34	2026-08-04 15:23:00.00087+00	3	Братос: перший важкий бій, порятунок пораненого,	1	[{"added": {}}]	10	2
35	2026-08-04 15:23:31.225439+00	4	Макс: академія, дружба, спорт, відвага, добров	1	[{"added": {}}]	10	2
36	2026-08-04 15:24:39.5989+00	5	Юджин: порятунок під водою.	1	[{"added": {}}]	10	2
37	2026-08-04 15:24:48.138302+00	1	Alex: Test processa spogadiv	3		10	2
38	2026-08-04 16:58:24.789645+00	1	фadmin	3		4	2
39	2026-08-05 05:28:27.138716+00	1	ГЕРОЙ УКРАЇНИ Боровицький Назар Богданович	1	[{"added": {}}]	13	2
40	2026-08-05 05:57:55.653551+00	2	Вікіпедія	1	[{"added": {}}]	13	2
41	2026-08-05 06:32:00.736311+00	1	Borovitskyi Nazar	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u0434\\u0435\\u043c\\u043e-\\u043f\\u043b\\u0430\\u0448\\u043a\\u0443"]}}]	7	2
42	2026-08-05 06:32:17.413488+00	1	Borovitskyi Nazar	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u0434\\u0435\\u043c\\u043e-\\u043f\\u043b\\u0430\\u0448\\u043a\\u0443"]}}]	7	2
43	2026-08-05 10:51:00.268101+00	1	Подвиг і служба	1	[{"added": {}}]	15	2
81	2026-08-14 13:54:28.071135+00	1	Відео	2	[]	14	2
44	2026-08-05 11:59:53.928597+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u0417\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u0441\\u0442\\u043e\\u0440\\u0456\\u043d\\u043a\\u0438"]}}]	15	2
45	2026-08-05 12:10:37.572864+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0438\\u0441 \\u0443 \\u043f\\u0435\\u0440\\u0448\\u043e\\u043c\\u0443 \\u0435\\u043a\\u0440\\u0430\\u043d\\u0456", "\\u041e\\u0441\\u043d\\u043e\\u0432\\u043d\\u0438\\u0439 \\u043e\\u043f\\u0438\\u0441 \\u0441\\u043b\\u0443\\u0436\\u0431\\u0438", "\\u0414\\u043e\\u0434\\u0430\\u0442\\u043a\\u043e\\u0432\\u0438\\u0439 \\u0442\\u0435\\u043a\\u0441\\u0442", "\\u0420\\u0435\\u0434\\u0430\\u043a\\u0446\\u0456\\u0439\\u043d\\u0430 \\u043f\\u0440\\u0438\\u043c\\u0456\\u0442\\u043a\\u0430", "\\u041d\\u043e\\u043c\\u0435\\u0440 \\u0443\\u043a\\u0430\\u0437\\u0443"]}}]	15	2
46	2026-08-05 12:19:14.509766+00	1	ГЕРОЙ УКРАЇНИ	2	[{"changed": {"fields": ["\\u0417\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u043c\\u0430\\u0442\\u0435\\u0440\\u0456\\u0430\\u043b\\u0443", "\\u041d\\u0430\\u0437\\u0432\\u0430 \\u0434\\u0436\\u0435\\u0440\\u0435\\u043b\\u0430"]}}]	13	2
47	2026-08-05 12:19:42.237861+00	2	ГЕРОЙ УКРАЇНИ	2	[{"changed": {"fields": ["\\u0417\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u043c\\u0430\\u0442\\u0435\\u0440\\u0456\\u0430\\u043b\\u0443"]}}]	13	2
48	2026-08-05 12:30:03.246253+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u0417\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u043c\\u0430\\u0442\\u0435\\u0440\\u0456\\u0430\\u043b\\u0443", "\\u041d\\u0430\\u0437\\u0432\\u0430 \\u0434\\u0436\\u0435\\u0440\\u0435\\u043b\\u0430", "\\u041a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0456\\u044f"]}}]	13	2
49	2026-08-05 12:30:27.633678+00	2	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u0417\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u043c\\u0430\\u0442\\u0435\\u0440\\u0456\\u0430\\u043b\\u0443", "\\u041a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0456\\u044f"]}}]	13	2
50	2026-08-05 12:41:51.435363+00	1	1	2	[{"changed": {"fields": ["\\u0420\\u0435\\u043a\\u043e\\u043c\\u0435\\u043d\\u0434\\u043e\\u0432\\u0430\\u043d\\u0435 \\u0432\\u0456\\u0434\\u0435\\u043e"]}}]	9	2
51	2026-08-05 12:45:39.651114+00	2	video	1	[{"added": {}}]	9	2
52	2026-08-05 12:46:05.21349+00	2	video	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0456\\u044f"]}}]	9	2
53	2026-08-05 12:46:27.575816+00	1	1	2	[{"changed": {"fields": ["\\u0420\\u0435\\u043a\\u043e\\u043c\\u0435\\u043d\\u0434\\u043e\\u0432\\u0430\\u043d\\u0435 \\u0432\\u0456\\u0434\\u0435\\u043e"]}}]	9	2
54	2026-08-05 12:47:06.124422+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u043d\\u0430 \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u0456\\u0439"]}}]	13	2
55	2026-08-05 12:47:39.89081+00	2	video	2	[{"changed": {"fields": ["\\u041e\\u0431\\u043a\\u043b\\u0430\\u0434\\u0438\\u043d\\u043a\\u0430", "\\u0420\\u0435\\u043a\\u043e\\u043c\\u0435\\u043d\\u0434\\u043e\\u0432\\u0430\\u043d\\u0435 \\u0432\\u0456\\u0434\\u0435\\u043e"]}}]	9	2
56	2026-08-07 14:14:44.083638+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430 \\u0441\\u0430\\u0439\\u0442\\u0443", "\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u0434\\u0435\\u043c\\u043e-\\u043f\\u043b\\u0430\\u0448\\u043a\\u0443"]}}]	7	2
57	2026-08-07 14:15:24.203423+00	1	Nazar Borovytskyi	2	[]	7	2
58	2026-08-07 14:17:13.467084+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u0442\\u0440\\u0435\\u0442", "\\u041a\\u043b\\u044e\\u0447\\u043e\\u0432\\u0430 \\u0446\\u0438\\u0442\\u0430\\u0442\\u0430", "\\u041a\\u043e\\u0440\\u043e\\u0442\\u043a\\u0438\\u0439 \\u043e\\u043f\\u0438\\u0441 (\\u0434\\u043b\\u044f \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u043e\\u0457)"]}}]	8	2
59	2026-08-07 21:00:31.785582+00	2	Фото #2	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
60	2026-08-07 21:00:52.72775+00	6	Фото #6	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
61	2026-08-07 21:01:26.957607+00	2	Фото #2	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
62	2026-08-07 21:01:45.016389+00	6	Фото #6	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
63	2026-08-07 21:01:50.506783+00	1	Фото #1	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
64	2026-08-07 21:01:57.84217+00	4	Фото #4	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
65	2026-08-07 21:02:03.695078+00	3	Фото #3	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
66	2026-08-07 21:02:29.695097+00	2	Фото #2	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
67	2026-08-07 21:02:43.906679+00	2	Фото #2	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
68	2026-08-07 21:03:08.276068+00	3	Фото #3	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
69	2026-08-07 21:03:26.790453+00	3	Фото #3	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
70	2026-08-07 21:03:47.602465+00	4	Фото #4	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
71	2026-08-07 21:03:47.603622+00	3	Фото #3	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
72	2026-08-07 21:04:12.310986+00	3	Фото #3	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
73	2026-08-07 21:04:47.870475+00	4	Фото #4	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
74	2026-08-13 17:29:05.431712+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0433\\u043e\\u0440\\u043e\\u0434\\u0430 (\\u043a\\u043e\\u0440\\u043e\\u0442\\u043a\\u043e)"]}}]	8	2
75	2026-08-13 17:29:52.399465+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u0412\\u0441\\u0442\\u0443\\u043f\\u043d\\u0438\\u0439 \\u0442\\u0435\\u043a\\u0441\\u0442 \\u043d\\u0430 \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u0456\\u0439"]}}]	8	2
76	2026-08-13 17:30:20.962563+00	5	2008/2009–2011 — фвфв	1	[{"added": {}}]	11	2
77	2026-08-13 17:31:00.588057+00	1	Боровицький Назар Богданович	2	[{"changed": {"fields": ["\\u041a\\u043b\\u044e\\u0447\\u043e\\u0432\\u0430 \\u0446\\u0438\\u0442\\u0430\\u0442\\u0430"]}}]	8	2
78	2026-08-13 17:41:19.065465+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0438\\u0441 \\u0443 \\u043f\\u0435\\u0440\\u0448\\u043e\\u043c\\u0443 \\u0435\\u043a\\u0440\\u0430\\u043d\\u0456"]}}]	15	2
79	2026-08-14 13:51:35.448963+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u0443 \\u0444\\u0443\\u0442\\u0435\\u0440\\u0456"]}}]	7	2
80	2026-08-14 13:53:24.233687+00	1	Відео	1	[{"added": {}}]	14	2
82	2026-08-14 14:08:17.268609+00	2	Гречка: командирство, наставництво, підготовка д	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u0443\\u0432\\u0430\\u0442\\u0438 \\u043d\\u0430 \\u0433\\u043e\\u043b\\u043e\\u0432\\u043d\\u0456\\u0439"]}}]	10	2
83	2026-08-14 16:10:05.967572+00	2	Головна	1	[{"added": {}}]	14	2
84	2026-08-20 11:03:26.897639+00	5	2008/2009–2011 — фвфв	3		11	2
85	2026-08-20 11:06:09.352709+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0438\\u0441 \\u0443 \\u043f\\u0435\\u0440\\u0448\\u043e\\u043c\\u0443 \\u0435\\u043a\\u0440\\u0430\\u043d\\u0456"]}}]	15	2
86	2026-08-20 11:07:08.95571+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0438\\u0441 \\u0443 \\u043f\\u0435\\u0440\\u0448\\u043e\\u043c\\u0443 \\u0435\\u043a\\u0440\\u0430\\u043d\\u0456"]}}]	15	2
87	2026-08-20 11:09:11.095347+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0438\\u0441 \\u0443 \\u043f\\u0435\\u0440\\u0448\\u043e\\u043c\\u0443 \\u0435\\u043a\\u0440\\u0430\\u043d\\u0456", "\\u041e\\u0441\\u043d\\u043e\\u0432\\u043d\\u0438\\u0439 \\u043e\\u043f\\u0438\\u0441 \\u0441\\u043b\\u0443\\u0436\\u0431\\u0438", "\\u0414\\u043e\\u0434\\u0430\\u0442\\u043a\\u043e\\u0432\\u0438\\u0439 \\u0442\\u0435\\u043a\\u0441\\u0442", "\\u0420\\u0435\\u0434\\u0430\\u043a\\u0446\\u0456\\u0439\\u043d\\u0430 \\u043f\\u0440\\u0438\\u043c\\u0456\\u0442\\u043a\\u0430"]}}]	15	2
88	2026-08-20 11:10:03.270512+00	1	Подвиг і с лужба	2	[{"changed": {"fields": ["\\u041e\\u0441\\u043d\\u043e\\u0432\\u043d\\u0438\\u0439 \\u043e\\u043f\\u0438\\u0441 \\u0441\\u043b\\u0443\\u0436\\u0431\\u0438", "\\u0414\\u043e\\u0434\\u0430\\u0442\\u043a\\u043e\\u0432\\u0438\\u0439 \\u0442\\u0435\\u043a\\u0441\\u0442"]}}]	15	2
89	2026-08-20 14:04:17.831306+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430 \\u0440\\u043e\\u0437\\u0434\\u0456\\u043b\\u0443 \\u00ab\\u0423 \\u0417\\u041c\\u0406\\u00bb"]}}]	7	2
90	2026-08-20 14:26:50.609838+00	1	Nazar Borovytskyi	2	[]	7	2
91	2026-08-20 18:40:59.049892+00	1	Nazar Borovytskyi	2	[]	7	2
92	2026-08-20 18:48:56.384423+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u0413\\u043e\\u043b\\u043e\\u0432\\u043d\\u0430 \\u2014 \\u0442\\u0435\\u043a\\u0441\\u0442 \\u043d\\u0430\\u0434 \\u0456\\u043c\\u2019\\u044f\\u043c"]}}]	7	2
93	2026-08-20 18:49:16.980925+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u0413\\u043e\\u043b\\u043e\\u0432\\u043d\\u0430 \\u2014 \\u0442\\u0435\\u043a\\u0441\\u0442 \\u043d\\u0430\\u0434 \\u0456\\u043c\\u2019\\u044f\\u043c"]}}]	7	2
94	2026-08-20 19:00:11.612231+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u0416\\u0438\\u0442\\u0442\\u044f \\u2014 \\u043d\\u0430\\u0434\\u0437\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a"]}}]	7	2
95	2026-08-20 19:00:40.85857+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u0416\\u0438\\u0442\\u0442\\u044f \\u2014 \\u043d\\u0430\\u0434\\u0437\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a"]}}]	7	2
96	2026-08-20 19:06:53.666907+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0434\\u0432\\u0438\\u0433 \\u0456 \\u0441\\u043b\\u0443\\u0436\\u0431\\u0430 \\u2014 \\u0437\\u0430\\u0433\\u043e\\u043b\\u043e\\u0432\\u043e\\u043a \\u0431\\u043b\\u043e\\u043a\\u0443 \\u0441\\u043b\\u0443\\u0436\\u0431\\u0438"]}}]	7	2
97	2026-08-26 21:01:56.206373+00	6	1993 — Народився	1	[{"added": {}}]	11	2
98	2026-08-27 15:22:29.383341+00	6	Фото #6	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
99	2026-08-27 15:22:34.924686+00	1	Фото #1	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
100	2026-08-27 15:22:40.51203+00	3	Фото #3	2	[]	12	2
101	2026-08-27 15:22:46.963018+00	4	Фото #4	2	[{"changed": {"fields": ["\\u0420\\u043e\\u0437\\u043c\\u0456\\u0440 \\u0443 \\u0441\\u0456\\u0442\\u0446\\u0456"]}}]	12	2
102	2026-08-27 18:32:05.107794+00	2	Фото #2	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
103	2026-08-27 18:32:21.085128+00	1	Фото #1	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
104	2026-08-27 18:32:27.063419+00	6	Фото #6	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
105	2026-08-27 18:33:05.725654+00	4	Фото #4	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
106	2026-08-27 18:33:20.654313+00	3	Фото #3	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
107	2026-08-27 18:33:44.043816+00	3	Фото #3	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
108	2026-08-27 18:34:03.50762+00	3	Фото #3	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
109	2026-08-27 18:34:10.154823+00	1	Фото #1	2	[{"changed": {"fields": ["\\u041f\\u043e\\u0440\\u044f\\u0434\\u043e\\u043a"]}}]	12	2
110	2026-08-27 18:55:46.683762+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u041b\\u0456\\u0442\\u0435\\u0440\\u0430 \\u043b\\u043e\\u0433\\u043e\\u0442\\u0438\\u043f\\u0430"]}}]	7	2
111	2026-08-27 20:58:56.064757+00	7	Фото #7	1	[{"added": {}}]	12	2
112	2026-08-27 20:59:19.818763+00	8	Фото #8	1	[{"added": {}}]	12	2
113	2026-08-27 20:59:37.462511+00	9	Фото #9	1	[{"added": {}}]	12	2
114	2026-08-27 20:59:56.012601+00	10	Фото #10	1	[{"added": {}}]	12	2
115	2026-08-27 21:00:04.634101+00	10	Фото #10	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0443\\u0431\\u043b\\u0456\\u043a\\u043e\\u0432\\u0430\\u043d\\u043e"]}}]	12	2
116	2026-08-27 21:00:32.981695+00	11	Фото #11	1	[{"added": {}}]	12	2
117	2026-08-27 21:37:09.139272+00	12	Фото #12	1	[{"added": {}}]	12	2
118	2026-08-27 21:58:45.219211+00	13	Фото #13	1	[{"added": {}}]	12	2
119	2026-08-28 07:23:18.55068+00	1	Nazar Borovytskyi	2	[{"changed": {"fields": ["\\u0416\\u0438\\u0442\\u0442\\u044f \\u2014 \\u043e\\u043f\\u0438\\u0441"]}}]	7	2
120	2026-08-28 11:48:23.037462+00	3	уаіуау	1	[{"added": {}}]	9	2
121	2026-08-28 11:48:41.09283+00	4	фув	1	[{"added": {}}]	9	2
122	2026-08-29 19:19:17.736362+00	6	Тестовий спогад: Назар був тією людиною, яка робить склад	2	[{"changed": {"fields": ["\\u0406\\u043c\\u02bc\\u044f", "\\u0422\\u0435\\u043a\\u0441\\u0442 \\u0441\\u043f\\u043e\\u0433\\u0430\\u0434\\u0443"]}}]	10	2
123	2026-08-29 19:32:29.195986+00	7	dgstgs: Назар прийшов вести гурток у нашій школі	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u0441\\u043f\\u043e\\u0433\\u0430\\u0434\\u0443"]}}]	10	2
124	2026-08-29 19:32:54.026644+00	4	Макс: Ми служили разом три роки, і за весь цей	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043a\\u0441\\u0442 \\u0441\\u043f\\u043e\\u0433\\u0430\\u0434\\u0443"]}}]	10	2
125	2026-08-29 19:33:28.152826+00	10	1: 1	1	[{"added": {}}]	10	2
126	2026-08-29 19:33:41.034635+00	11	1: 11	1	[{"added": {}}]	10	2
127	2026-08-29 19:33:48.394549+00	12	1: 11	1	[{"added": {}}]	10	2
128	2026-08-29 19:33:54.6592+00	13	1: 1	1	[{"added": {}}]	10	2
129	2026-08-29 19:34:37.31494+00	13	1: 1	2	[{"changed": {"fields": ["\\u0421\\u0442\\u0430\\u0442\\u0443\\u0441"]}}]	10	2
130	2026-08-29 20:55:42.319785+00	3	Братос: перший важкий бій, порятунок пораненого,	2	[]	10	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	sitesettings
8	biography	biography
9	videos	video
10	memories	memory
11	biography	timelineevent
12	gallery	photo
13	media_mentions	mediamention
14	seo	seopage
15	pages	servicepage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-31 11:14:40.933592+00
2	auth	0001_initial	2026-07-31 11:14:40.955303+00
3	admin	0001_initial	2026-07-31 11:14:40.961358+00
4	admin	0002_logentry_remove_auto_add	2026-07-31 11:14:40.96353+00
5	admin	0003_logentry_add_action_flag_choices	2026-07-31 11:14:40.9658+00
6	contenttypes	0002_remove_content_type_name	2026-07-31 11:14:40.971783+00
7	auth	0002_alter_permission_name_max_length	2026-07-31 11:14:40.975416+00
8	auth	0003_alter_user_email_max_length	2026-07-31 11:14:40.978119+00
9	auth	0004_alter_user_username_opts	2026-07-31 11:14:40.980895+00
10	auth	0005_alter_user_last_login_null	2026-07-31 11:14:40.983651+00
11	auth	0006_require_contenttypes_0002	2026-07-31 11:14:40.984162+00
12	auth	0007_alter_validators_add_error_messages	2026-07-31 11:14:40.989135+00
13	auth	0008_alter_user_username_max_length	2026-07-31 11:14:40.993791+00
14	auth	0009_alter_user_last_name_max_length	2026-07-31 11:14:40.997372+00
15	auth	0010_alter_group_name_max_length	2026-07-31 11:14:41.001516+00
16	auth	0011_update_proxy_permissions	2026-07-31 11:14:41.004569+00
17	auth	0012_alter_user_first_name_max_length	2026-07-31 11:14:41.007726+00
18	sessions	0001_initial	2026-07-31 11:14:41.01182+00
19	core	0001_initial	2026-08-03 12:41:43.569143+00
20	biography	0001_initial	2026-08-04 09:55:40.5051+00
21	videos	0001_initial	2026-08-04 11:18:13.75277+00
22	memories	0001_initial	2026-08-04 12:56:03.206294+00
23	biography	0002_timelineevent_biography_award_title_and_more	2026-08-04 12:59:21.631067+00
24	core	0002_sitesettings_site_title_and_more	2026-08-04 12:59:21.635388+00
25	gallery	0001_initial	2026-08-04 12:59:21.637792+00
26	media_mentions	0001_initial	2026-08-04 12:59:21.639704+00
27	seo	0001_initial	2026-08-04 12:59:21.644822+00
28	gallery	0002_photo_alt_text_photo_category_photo_is_published	2026-08-04 14:26:23.078727+00
29	videos	0002_remove_video_embed_url_video_category_and_more	2026-08-04 14:52:00.758978+00
30	videos	0003_alter_video_video_file	2026-08-04 14:57:25.849892+00
31	pages	0001_initial	2026-08-05 10:41:53.133118+00
32	media_mentions	0002_mediamention_category_mediamention_is_published_and_more	2026-08-05 12:18:10.48234+00
33	media_mentions	0003_alter_mediamention_title	2026-08-05 12:20:42.757196+00
34	media_mentions	0004_mediamention_is_featured	2026-08-05 12:40:59.800897+00
35	core	0003_sitesettings_biography_title_and_more	2026-08-08 08:23:39.125798+00
36	biography	0003_timelineevent_biography	2026-08-13 16:47:52.244996+00
37	gallery	0003_alter_photo_options	2026-08-13 17:49:13.820229+00
38	media_mentions	0005_alter_mediamention_options	2026-08-13 20:34:51.976838+00
39	biography	0004_alter_biography_rank_alter_biography_signature_quote	2026-08-18 09:59:02.226654+00
40	core	0004_remove_sitesettings_biography_title_and_more	2026-08-20 13:57:54.51081+00
41	core	0005_sitesettings_home_empty_text_and_more	2026-08-20 18:37:38.648482+00
42	core	0006_sitesettings_life_empty_biography_text_and_more	2026-08-20 18:52:35.815467+00
43	core	0007_sitesettings_service_award_title_and_more	2026-08-20 19:02:19.157322+00
44	core	0008_sitesettings_photos_category_empty_text_and_more	2026-08-20 19:10:26.494585+00
45	core	0009_sitesettings_videos_accessibility_label_and_more	2026-08-20 19:14:08.618239+00
46	core	0010_sitesettings_media_empty_text_and_more	2026-08-20 19:17:28.158065+00
47	core	0011_sitesettings_memories_empty_text_and_more	2026-08-20 19:21:39.584433+00
48	gallery	0004_alter_photo_layout_size	2026-08-29 18:49:46.431222+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
qu1mwhojcc3mgklqq8q5jj8tnmd2wrxq	.eJxVjMsOwiAQRf-FtSGADA-X7vsNZBhAqgaS0q6M_65NutDtPefcFwu4rTVsIy9hTuzCFDv9bhHpkdsO0h3brXPqbV3myHeFH3Twqaf8vB7u30HFUb91BCpkY0QQIBU4aQt4QWic96oI5Ukap0kYCwnBKVO0zlhQWYAzCWDvD9nUN0g:1wrEyM:eHIkw5cBQfWQDd6JgHt_tW26jI9ikY1zBlyoN60HkLE	2026-08-18 13:14:22.50261+00
pyz46xwlb6kcehr5rphbvovvq4hhnxt0	.eJxVjMsOwiAQRf-FtSGADA-X7vsNZBhAqgaS0q6M_65NutDtPefcFwu4rTVsIy9hTuzCFDv9bhHpkdsO0h3brXPqbV3myHeFH3Twqaf8vB7u30HFUb91BCpkY0QQIBU4aQt4QWic96oI5Ukap0kYCwnBKVO0zlhQWYAzCWDvD9nUN0g:1wyquC:4rTfajWj1EhIR_BWRB6iyrAncVTQwfUzFhnVcMykSyE	2026-09-08 13:09:32.814355+00
il9rtczdhkmpe6b0wuwq750zg2a143pt	.eJxVjDsOwjAQBe_iGlmxY2tjSnrOYO3HiwMokeKkQtwdIqWA9s3Me5mM21rz1sqSRzFn483pdyPkR5l2IHecbrPleVqXkeyu2IM2e52lPC-H-3dQsdVvTepIIrMjjBIIUteFIUSOJRbtyRP0ANHBEMCLsiQFYlT1mBImVfP-AANeOQQ:1x0OVV:8TdCQgLDL1ijAWlCI3fokLlFs_8NSRKhS8FEAkoah4I	2026-09-12 19:14:25.012116+00
\.


--
-- Data for Name: gallery_photo; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.gallery_photo (id, image, caption, layout_size, "order", alt_text, category, is_published) FROM stdin;
2	gallery/IMG_9408.JPG			2		study	t
6	gallery/IMG_5964.JPG			3		memory	t
4	gallery/IMG_7336.JPG			4		study	t
3	gallery/IMG_2396.JPG			1		service	t
1	gallery/IMG_5963.JPG			5		family	t
7	gallery/IMG_9186.JPG			0		service	t
8	gallery/IMG_9408_wD13AnB.JPG			0		service	t
9	gallery/IMG_5963_tUujXgF.JPG			0		study	t
10	gallery/IMG_2396_Q095i6c.JPG			0		service	t
11	gallery/IMG_5963_n3BE35b.JPG			0		family	t
12	gallery/IMG_7336_ggwkoy3.JPG			0		service	t
13	gallery/IMG_9186_A1RkX0z.JPG			0		family	t
\.


--
-- Data for Name: media_mentions_mediamention; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.media_mentions_mediamention (id, source_name, url, published_date, "order", category, is_published, title, is_featured) FROM stdin;
2	Вікіпедія	https://uk.wikipedia.org/wiki/%D0%91%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9_%D0%9D%D0%B0%D0%B7%D0%B0%D1%80_%D0%91%D0%BE%D0%B3%D0%B4%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87	2026-06-09	2	official	t	Боровицький Назар Богданович	f
1	ГЕРОЙ УКРАЇНИ	https://gur.gov.ua/content/nazar-borovytskyi.html	\N	1	official	t	Боровицький Назар Богданович	t
\.


--
-- Data for Name: memories_memory; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.memories_memory (id, author_name, author_role, text, featured, status, created_at) FROM stdin;
5	Юджин	Побратим	порятунок під водою.	f	approved	2026-08-04 15:24:39.597555+00
2	Гречка	Побратим	командирство, наставництво, підготовка до вторгнення, Київщина, рішення летіти до Маріуполя.	t	approved	2026-08-04 15:22:33.739587+00
6	Тестовий спогад	Побратим	Назар був тією людиною, яка робить складні речі буденно. Не пам'ятаю, щоб він\r\nколись підвищував голос або сперечався заради того, щоб виграти суперечку.\r\nВін просто робив і мовчав. У нього була дивна звичка: перед кожним виїздом\r\nперевіряти спорядження двічі, навіть якщо щойно його склав. Ми жартували, що\r\nце параноя, а він відповідав, що це повага до тих, хто поруч. Коли його не\r\nстало, я зловив себе на тому, що теж перевіряю все двічі. Мабуть, так люди й\r\nзалишаються з нами — у	f	approved	2026-08-19 09:28:22.595037+00
8	Тестовий спогад 2	Побратим	Він завжди приходив на десять хвилин раніше. За всі роки — жодного разу\r\nінакше. Дрібниця, а я досі про це згадую.	f	approved	2026-08-29 19:23:17.929946+00
9	тест спогад3	Однокласник / однокурсник	Ми познайомилися на другому курсі, коли нас поставили в один наряд. Я тоді\r\nстрашенно не виспався і був злий на весь світ, а він усю ніч розповідав про\r\nгори — як збирається пройти Чорногірський хребет узимку. Через півроку ми\r\nтаки пішли. Він ніс найважчий рюкзак і жодного разу не поскаржився. Коли на\r\nспуску я підвернув ногу, він мовчки перекинув мої речі до себе. Оце і був\r\nувесь Назар: не говорив, що допоможе, — просто вже допомагав.	f	approved	2026-08-29 19:23:41.787774+00
7	dgstgs	Колега	Назар прийшов вести гурток у нашій школі на волонтерських засадах, коли сам\r\nнавчався на четвертому курсі. Дітей записалося восьмеро, приходило троє, і ми\r\nз колегами були певні, що він кине через місяць. Він відходив цілий рік —\r\nщосуботи, через два міста, за власні гроші на квитки. Коли я запитала навіщо,\r\nвін лише знизав плечима: «Мене колись теж хтось учив». Двоє з тих трьох\r\nхлопців зараз служать, і обидва казали мені, що пішли саме через нього.	f	approved	2026-08-19 09:28:32.495135+00
4	Макс	Друг	Ми служили разом три роки, і за весь цей час я жодного разу не бачив, щоб він\r\nпоспішав. Навіть коли всі навколо бігали, він рухався рівно — і саме тому\r\nвстигав першим. Одного разу ми просиділи в підвалі майже добу, і він усю ніч\r\nрозповідав про доньку сусідів, яка малює котів у скафандрах. Я тоді зрозумів,\r\nщо він тримає нас не наказами, а от цими розмовами про звичайне життя, яке\r\nдесь триває без нас. Він умів нагадати, заради чого ми взагалі там опинилися.	f	approved	2026-08-04 15:23:31.224177+00
12	1	1	11	f	rejected	2026-08-29 19:33:48.393742+00
10	1	1	1	f	rejected	2026-08-29 19:33:28.151253+00
11	1	1	11	f	rejected	2026-08-29 19:33:41.033954+00
13	1	1	1	f	approved	2026-08-29 19:33:54.658624+00
3	Братос	Побратим	перший важкий бій, порятунок пораненого, чесність і принциповість.	f	approved	2026-08-04 15:22:59.999669+00
\.


--
-- Data for Name: pages_servicepage; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.pages_servicepage (id, hero_eyebrow, hero_title, hero_description, publication_status, service_intro, service_text, editorial_note, award_title, award_subtitle, decree_date, decree_number, decree_source_name, decree_url, is_published, updated_at) FROM stdin;
1	Офіційно узгоджений розділ	Подвиг і с лужба	Майор Головного управління розвідки Міністерства оборони України	approved	Медаль «За відвагу»\r\nОрден «За мужність» III ступеня\r\nОрден Богдана Хмельницького III ступеня	Відзнака за участь в Антитерористичній операції\r\nВідзнака «Захисник України» (за мужність, відвагу, честь)\r\nВідзнака «За мужність при виконанні спецзавдань»		Звання Герой України	з удостоєнням ордена «Золота Зірка»	2025-06-18	1112	president.gov.ua		t	2026-08-20 11:10:03.269559+00
\.


--
-- Data for Name: seo_seopage; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.seo_seopage (id, page_key, title, description, og_image) FROM stdin;
1	videos			
2	home			seo/apple-touch-icon.png
\.


--
-- Data for Name: videos_video; Type: TABLE DATA; Schema: public; Owner: memorial
--

COPY public.videos_video (id, title, thumbnail, "order", category, created_at, description, duration, is_featured, is_published, recorded_at, transcript, video_file) FROM stdin;
2	video	videos/thumbnails/IMG_2396.JPG	1	media	2026-08-05 12:45:39.649273+00	non		t	t	2002		videos/files/27706-365890968_medium_6ODRgyM.mp4
1	1		1	media	2026-08-04 14:56:44.434191+00	1		f	t			videos/files/27706-365890968_medium.mp4
3	уаіуау		0	media	2026-08-28 11:48:23.03589+00			f	t			videos/files/27706-365890968_medium_WNRZUxA.mp4
4	фув		0	memory	2026-08-28 11:48:41.092054+00			f	t			videos/files/27706-365890968_medium_dU8gSin.mp4
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: biography_biography_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.biography_biography_id_seq', 1, true);


--
-- Name: biography_timelineevent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.biography_timelineevent_id_seq', 6, true);


--
-- Name: core_sitesettings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.core_sitesettings_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 130, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 48, true);


--
-- Name: gallery_photo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.gallery_photo_id_seq', 13, true);


--
-- Name: media_mentions_mediamention_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.media_mentions_mediamention_id_seq', 2, true);


--
-- Name: memories_memory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.memories_memory_id_seq', 13, true);


--
-- Name: pages_servicepage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.pages_servicepage_id_seq', 1, true);


--
-- Name: seo_seopage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.seo_seopage_id_seq', 2, true);


--
-- Name: videos_video_id_seq; Type: SEQUENCE SET; Schema: public; Owner: memorial
--

SELECT pg_catalog.setval('public.videos_video_id_seq', 4, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: biography_biography biography_biography_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.biography_biography
    ADD CONSTRAINT biography_biography_pkey PRIMARY KEY (id);


--
-- Name: biography_timelineevent biography_timelineevent_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.biography_timelineevent
    ADD CONSTRAINT biography_timelineevent_pkey PRIMARY KEY (id);


--
-- Name: core_sitesettings core_sitesettings_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.core_sitesettings
    ADD CONSTRAINT core_sitesettings_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: gallery_photo gallery_photo_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.gallery_photo
    ADD CONSTRAINT gallery_photo_pkey PRIMARY KEY (id);


--
-- Name: media_mentions_mediamention media_mentions_mediamention_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.media_mentions_mediamention
    ADD CONSTRAINT media_mentions_mediamention_pkey PRIMARY KEY (id);


--
-- Name: memories_memory memories_memory_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.memories_memory
    ADD CONSTRAINT memories_memory_pkey PRIMARY KEY (id);


--
-- Name: pages_servicepage pages_servicepage_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.pages_servicepage
    ADD CONSTRAINT pages_servicepage_pkey PRIMARY KEY (id);


--
-- Name: seo_seopage seo_seopage_page_key_key; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.seo_seopage
    ADD CONSTRAINT seo_seopage_page_key_key UNIQUE (page_key);


--
-- Name: seo_seopage seo_seopage_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.seo_seopage
    ADD CONSTRAINT seo_seopage_pkey PRIMARY KEY (id);


--
-- Name: videos_video videos_video_pkey; Type: CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.videos_video
    ADD CONSTRAINT videos_video_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: biography_timelineevent_biography_id_9bf9c46c; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX biography_timelineevent_biography_id_9bf9c46c ON public.biography_timelineevent USING btree (biography_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: seo_seopage_page_key_4c84a77f_like; Type: INDEX; Schema: public; Owner: memorial
--

CREATE INDEX seo_seopage_page_key_4c84a77f_like ON public.seo_seopage USING btree (page_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: biography_timelineevent biography_timelineev_biography_id_9bf9c46c_fk_biography; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.biography_timelineevent
    ADD CONSTRAINT biography_timelineev_biography_id_9bf9c46c_fk_biography FOREIGN KEY (biography_id) REFERENCES public.biography_biography(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: memorial
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict Bctk5BQwexLgV0IxNrU8wadAgRQnrUUF9QQTkzmAC6DJ0P6RRTYlss0Qdfh7Pgm

