# Generated by Django 6.0.7 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(
                default="Memorial", max_length=200, verbose_name="Назва сайту"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_letter",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Літера логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="copyright_holder",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Правовласник у копірайті"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="demo_strip_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Стрічка «Демонстраційний макет» під шапкою. Вимкнути перед передачею родині.",
                verbose_name="Показувати демо-плашку",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.TextField(blank=True, verbose_name="Текст у футері"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Назва в шапці"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Підзаголовок у шапці"
            ),
        ),
    ]
