# Generated by Django 6.0.7 on 2026-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_site_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='biography_title',
            field=models.CharField(default='Життєпис', max_length=100, verbose_name='Назва розділу «Життєпис»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_title',
            field=models.CharField(default='Галерея', max_length=100, verbose_name='Назва розділу «Галерея»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_title',
            field=models.CharField(default='Спогади', max_length=100, verbose_name='Назва розділу «Спогади»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='publications_title',
            field=models.CharField(default='Публікації', max_length=100, verbose_name='Назва розділу «Публікації»'),
        ),
    ]
