# Generated by Django 6.0.7 on 2026-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_biography_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='biography_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='gallery_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='publications_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title',
            field=models.CharField(default='Головна', max_length=100, verbose_name='Назва розділу «Головна»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_title',
            field=models.CharField(default='Життя', max_length=100, verbose_name='Назва розділу «Життя»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_title',
            field=models.CharField(default='У ЗМІ', max_length=100, verbose_name='Назва розділу «У ЗМІ»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_title',
            field=models.CharField(default='Фото', max_length=100, verbose_name='Назва розділу «Фото»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_title',
            field=models.CharField(default='Подвиг і служба', max_length=100, verbose_name='Назва розділу «Подвиг і служба»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_title',
            field=models.CharField(default='Відео', max_length=100, verbose_name='Назва розділу «Відео»'),
        ),
    ]
