# Generated by Django 6.0.7 on 2026-08-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitesettings_biography_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_empty_text',
            field=models.TextField(default='Інформація ще готується до публікації.', verbose_name='Головна — текст без біографії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_empty_title',
            field=models.CharField(default='Сторінка пам’яті', max_length=200, verbose_name='Головна — заголовок без біографії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_empty_text',
            field=models.CharField(default='Фотоархів ще наповнюється', max_length=200, verbose_name='Головна — Фото: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_eyebrow',
            field=models.CharField(default='Фотоархів', max_length=100, verbose_name='Головна — Фото: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_title',
            field=models.CharField(default='Моменти життя', max_length=200, verbose_name='Головна — Фото: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_eyebrow',
            field=models.CharField(default='Світла пам’ять', max_length=100, verbose_name='Головна — текст над ім’ям'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_description',
            field=models.TextField(default='Біографія, важливі дати та підтверджені родиною події — без вигаданих деталей і зайвої публічності.', verbose_name='Головна — Життя: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_empty_text',
            field=models.CharField(default='Хронологію ще додають.', max_length=200, verbose_name='Головна — Життя: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_eyebrow',
            field=models.CharField(default='Його життя', max_length=100, verbose_name='Головна — Життя: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_title',
            field=models.CharField(default='Історія людини, яку пам’ятають', max_length=200, verbose_name='Головна — Життя: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_description',
            field=models.TextField(default='Добірка перевірених посилань на статті, новини та офіційні документи.', verbose_name='Головна — Матеріали: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_eyebrow',
            field=models.CharField(default='Публікації', max_length=100, verbose_name='Головна — Матеріали: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_title',
            field=models.CharField(default='Матеріали та офіційні джерела', max_length=200, verbose_name='Головна — Матеріали: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_video_description',
            field=models.TextField(default='Інтерв’ю, архівні записи та матеріали вшанування з короткими текстовими описами.', verbose_name='Головна — Відео: опис без відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_video_title',
            field=models.CharField(default='Голос і живі спогади', max_length=200, verbose_name='Головна — Відео: заголовок без відео'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='media_title',
            field=models.CharField(default='Посилання', max_length=100, verbose_name='Назва розділу «Посилання»'),
        ),
    ]
