# Generated by Django 6.0.7 on 2026-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_home_empty_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='life_empty_biography_text',
            field=models.TextField(default='Повний життєпис ще готується до публікації.', verbose_name='Життя — текст, якщо життєпис ще не додано'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_empty_page_text',
            field=models.TextField(default='Інформація для цієї сторінки ще готується.', verbose_name='Життя — текст, якщо інформація відсутня'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_hero_description',
            field=models.TextField(default='Людина поза подвигом: дитинство, навчання, родина, інтереси й підтверджена хронологія життя.', verbose_name='Життя — опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_hero_eyebrow',
            field=models.CharField(default='Про нього', max_length=100, verbose_name='Життя — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_photos_eyebrow',
            field=models.CharField(default='Фото до історії', max_length=100, verbose_name='Життя — Фото: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_photos_title',
            field=models.CharField(default='Роки, що залишилися у світлинах', max_length=200, verbose_name='Життя — Фото: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_description',
            field=models.TextField(default='До публікації додаються лише події з підтвердженими датами та формулюваннями.', verbose_name='Життя — Хронологія: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_empty_text',
            field=models.TextField(default='Підтверджені події з’являться тут після додавання через адміністративну панель.', verbose_name='Життя — Хронологія: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_empty_title',
            field=models.CharField(default='Хронологія ще наповнюється', max_length=200, verbose_name='Життя — Хронологія: заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_eyebrow',
            field=models.CharField(default='Хронологія', max_length=100, verbose_name='Життя — Хронологія: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_title',
            field=models.CharField(default='Ключові події', max_length=200, verbose_name='Життя — Хронологія: заголовок'),
        ),
    ]
