# Generated by Django 6.0.7 on 2026-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_life_empty_biography_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='service_award_title',
            field=models.CharField(default='Нагорода', max_length=200, verbose_name='Подвиг і служба — заголовок блоку нагороди'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_eyebrow',
            field=models.CharField(default='Перед публікацією', max_length=100, verbose_name='Подвиг і служба — Перевірка: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_1',
            field=models.CharField(default='Текст погоджено з частиною або пресслужбою.', max_length=300, verbose_name='Подвиг і служба — Перевірка: пункт 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_2',
            field=models.CharField(default='Дата й номер Указу звірені з офіційним джерелом.', max_length=300, verbose_name='Подвиг і служба — Перевірка: пункт 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_3',
            field=models.CharField(default='Немає координат, тактики, чисельності чи заборонених деталей.', max_length=300, verbose_name='Подвиг і служба — Перевірка: пункт 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_4',
            field=models.CharField(default='Формулювання схвалені родиною.', max_length=300, verbose_name='Подвиг і служба — Перевірка: пункт 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_title',
            field=models.CharField(default='Перевірка фактів і безпеки', max_length=200, verbose_name='Подвиг і служба — Перевірка: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_decree_link_text',
            field=models.CharField(default='Читати повний текст Указу', max_length=200, verbose_name='Подвиг і служба — текст посилання на Указ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_editorial_label',
            field=models.CharField(default='Редакційна позначка', max_length=150, verbose_name='Подвиг і служба — редакційна позначка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_empty_text',
            field=models.TextField(default='Інформація для цього розділу ще не додана.', verbose_name='Подвиг і служба — текст, якщо даних немає'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_safety_eyebrow',
            field=models.CharField(default='Безпека публікації', max_length=100, verbose_name='Подвиг і служба — Безпека: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_section_title',
            field=models.CharField(default='Опис служби', max_length=200, verbose_name='Подвиг і служба — заголовок блоку служби'),
        ),
    ]
