# Generated by Django 6.0.7 on 2026-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_service_award_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='photos_category_empty_text',
            field=models.CharField(default='У цій категорії поки немає фотографій.', max_length=250, verbose_name='Фото — текст порожньої категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_empty_text',
            field=models.TextField(default='Перевірені родиною фотографії з’являться тут після публікації.', verbose_name='Фото — текст порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_empty_title',
            field=models.CharField(default='Фотоархів ще наповнюється', max_length=200, verbose_name='Фото — заголовок порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_hero_description',
            field=models.TextField(default='Основний архів світлин, згрупований за періодами життя.', verbose_name='Фото — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_hero_title',
            field=models.CharField(default='Фотоархів', max_length=200, verbose_name='Фото — заголовок сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_verification_note',
            field=models.TextField(default='Кожне фото публікується лише після перевірки.', verbose_name='Фото — примітка про перевірку'),
        ),
    ]
