# Generated by Django 6.0.7 on 2026-08-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_photos_category_empty_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='videos_accessibility_label',
            field=models.CharField(default='Доступність:', max_length=100, verbose_name='Відео — заголовок примітки про доступність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_accessibility_text',
            field=models.TextField(default='за можливості до відео додається текстовий опис або розшифровка.', verbose_name='Відео — текст примітки про доступність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_admin_note',
            field=models.TextField(default='Усі матеріали додаються та публікуються тільки через адміністративну панель.', verbose_name='Відео — примітка про публікацію'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_all_records_label',
            field=models.CharField(default='Усі записи', max_length=100, verbose_name='Відео — надзаголовок архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_archive_title',
            field=models.CharField(default='Відеоархів', max_length=200, verbose_name='Відео — заголовок архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_empty_text',
            field=models.TextField(default='Перевірені відеоматеріали з’являться тут після публікації адміністратором.', verbose_name='Відео — текст порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_empty_title',
            field=models.CharField(default='Відеоархів ще наповнюється', max_length=200, verbose_name='Відео — заголовок порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_featured_label',
            field=models.CharField(default='Рекомендоване відео', max_length=150, verbose_name='Відео — підпис рекомендованого відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_hero_description',
            field=models.TextField(default='Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.', verbose_name='Відео — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_hero_eyebrow',
            field=models.CharField(default='Архівні записи', max_length=100, verbose_name='Відео — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_transcript_label',
            field=models.CharField(default='Текстовий опис відео', max_length=150, verbose_name='Відео — заголовок текстового опису'),
        ),
    ]
