# Generated by Django 6.0.7 on 2026-08-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_videos_accessibility_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='media_empty_text',
            field=models.TextField(default='Перевірені публікації та офіційні джерела з’являться тут пізніше.', verbose_name='Матеріали — текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_empty_title',
            field=models.CharField(default='Матеріалів поки немає', max_length=200, verbose_name='Матеріали — заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_hero_description',
            field=models.TextField(default='Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.', verbose_name='Матеріали — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_hero_eyebrow',
            field=models.CharField(default='Зовнішні джерела', max_length=100, verbose_name='Матеріали — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_section_title',
            field=models.CharField(default='Матеріали', max_length=200, verbose_name='Матеріали — заголовок розділу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_verification_note',
            field=models.TextField(default='Перевірка посилань рекомендована 1–2 рази на рік.', verbose_name='Матеріали — примітка про перевірку посилань'),
        ),
    ]
