# Generated by Django 6.0.7 on 2026-08-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_media_empty_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='memories_empty_text',
            field=models.TextField(default='Після перевірки модератором опубліковані спогади з’являться тут.', verbose_name='Спогади — текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_empty_title',
            field=models.CharField(default='Спогадів поки немає', max_length=200, verbose_name='Спогади — заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_hero_description',
            field=models.TextField(default='Слова родини, побратимів, друзів і однокласників.', verbose_name='Спогади — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_hero_eyebrow',
            field=models.CharField(default='Слова близьких', max_length=100, verbose_name='Спогади — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderation_label',
            field=models.CharField(default='Модерація', max_length=100, verbose_name='Спогади — блок модерації: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderation_note',
            field=models.TextField(default='Кожен текст публікується лише після ручної модерації.', verbose_name='Спогади — примітка про модерацію'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderator_text',
            field=models.CharField(default='Відповідальна особа від родини', max_length=200, verbose_name='Спогади — блок модерації: відповідальна особа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_description',
            field=models.TextField(default='Кожне повідомлення потрапляє на ручну модерацію й не з’являється на сайті автоматично.', verbose_name='Спогади — форма: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_eyebrow',
            field=models.CharField(default='Поділитися спогадом', max_length=100, verbose_name='Спогади — форма: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_title',
            field=models.CharField(default='Залиште кілька слів', max_length=200, verbose_name='Спогади — форма: заголовок'),
        ),
    ]
