# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_memories_empty_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_holder_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Правовласник у копірайті'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_holder_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Правовласник у копірайті'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_empty_text_en',
            field=models.TextField(default='Інформація ще готується до публікації.', null=True, verbose_name='Головна — текст без біографії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_empty_text_uk',
            field=models.TextField(default='Інформація ще готується до публікації.', null=True, verbose_name='Головна — текст без біографії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_empty_title_en',
            field=models.CharField(default='Сторінка пам’яті', max_length=200, null=True, verbose_name='Головна — заголовок без біографії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_empty_title_uk',
            field=models.CharField(default='Сторінка пам’яті', max_length=200, null=True, verbose_name='Головна — заголовок без біографії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_empty_text_en',
            field=models.CharField(default='Фотоархів ще наповнюється', max_length=200, null=True, verbose_name='Головна — Фото: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_empty_text_uk',
            field=models.CharField(default='Фотоархів ще наповнюється', max_length=200, null=True, verbose_name='Головна — Фото: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_eyebrow_en',
            field=models.CharField(default='Фотоархів', max_length=100, null=True, verbose_name='Головна — Фото: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_eyebrow_uk',
            field=models.CharField(default='Фотоархів', max_length=100, null=True, verbose_name='Головна — Фото: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_title_en',
            field=models.CharField(default='Моменти життя', max_length=200, null=True, verbose_name='Головна — Фото: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_title_uk',
            field=models.CharField(default='Моменти життя', max_length=200, null=True, verbose_name='Головна — Фото: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_eyebrow_en',
            field=models.CharField(default='Світла пам’ять', max_length=100, null=True, verbose_name='Головна — текст над ім’ям'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_eyebrow_uk',
            field=models.CharField(default='Світла пам’ять', max_length=100, null=True, verbose_name='Головна — текст над ім’ям'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_description_en',
            field=models.TextField(default='Біографія, важливі дати та підтверджені родиною події — без вигаданих деталей і зайвої публічності.', null=True, verbose_name='Головна — Життя: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_description_uk',
            field=models.TextField(default='Біографія, важливі дати та підтверджені родиною події — без вигаданих деталей і зайвої публічності.', null=True, verbose_name='Головна — Життя: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_empty_text_en',
            field=models.CharField(default='Хронологію ще додають.', max_length=200, null=True, verbose_name='Головна — Життя: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_empty_text_uk',
            field=models.CharField(default='Хронологію ще додають.', max_length=200, null=True, verbose_name='Головна — Життя: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_eyebrow_en',
            field=models.CharField(default='Його життя', max_length=100, null=True, verbose_name='Головна — Життя: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_eyebrow_uk',
            field=models.CharField(default='Його життя', max_length=100, null=True, verbose_name='Головна — Життя: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_title_en',
            field=models.CharField(default='Історія людини, яку пам’ятають', max_length=200, null=True, verbose_name='Головна — Життя: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_life_title_uk',
            field=models.CharField(default='Історія людини, яку пам’ятають', max_length=200, null=True, verbose_name='Головна — Життя: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_description_en',
            field=models.TextField(default='Добірка перевірених посилань на статті, новини та офіційні документи.', null=True, verbose_name='Головна — Матеріали: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_description_uk',
            field=models.TextField(default='Добірка перевірених посилань на статті, новини та офіційні документи.', null=True, verbose_name='Головна — Матеріали: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_eyebrow_en',
            field=models.CharField(default='Публікації', max_length=100, null=True, verbose_name='Головна — Матеріали: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_eyebrow_uk',
            field=models.CharField(default='Публікації', max_length=100, null=True, verbose_name='Головна — Матеріали: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_title_en',
            field=models.CharField(default='Матеріали та офіційні джерела', max_length=200, null=True, verbose_name='Головна — Матеріали: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_media_title_uk',
            field=models.CharField(default='Матеріали та офіційні джерела', max_length=200, null=True, verbose_name='Головна — Матеріали: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title_en',
            field=models.CharField(default='Головна', max_length=100, null=True, verbose_name='Назва розділу «Головна»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title_uk',
            field=models.CharField(default='Головна', max_length=100, null=True, verbose_name='Назва розділу «Головна»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_video_description_en',
            field=models.TextField(default='Інтерв’ю, архівні записи та матеріали вшанування з короткими текстовими описами.', null=True, verbose_name='Головна — Відео: опис без відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_video_description_uk',
            field=models.TextField(default='Інтерв’ю, архівні записи та матеріали вшанування з короткими текстовими описами.', null=True, verbose_name='Головна — Відео: опис без відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_video_title_en',
            field=models.CharField(default='Голос і живі спогади', max_length=200, null=True, verbose_name='Головна — Відео: заголовок без відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_video_title_uk',
            field=models.CharField(default='Голос і живі спогади', max_length=200, null=True, verbose_name='Головна — Відео: заголовок без відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_empty_biography_text_en',
            field=models.TextField(default='Повний життєпис ще готується до публікації.', null=True, verbose_name='Життя — текст, якщо життєпис ще не додано'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_empty_biography_text_uk',
            field=models.TextField(default='Повний життєпис ще готується до публікації.', null=True, verbose_name='Життя — текст, якщо життєпис ще не додано'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_empty_page_text_en',
            field=models.TextField(default='Інформація для цієї сторінки ще готується.', null=True, verbose_name='Життя — текст, якщо інформація відсутня'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_empty_page_text_uk',
            field=models.TextField(default='Інформація для цієї сторінки ще готується.', null=True, verbose_name='Життя — текст, якщо інформація відсутня'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_hero_description_en',
            field=models.TextField(default='Людина поза подвигом: дитинство, навчання, родина, інтереси й підтверджена хронологія життя.', null=True, verbose_name='Життя — опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_hero_description_uk',
            field=models.TextField(default='Людина поза подвигом: дитинство, навчання, родина, інтереси й підтверджена хронологія життя.', null=True, verbose_name='Життя — опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_hero_eyebrow_en',
            field=models.CharField(default='Про нього', max_length=100, null=True, verbose_name='Життя — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_hero_eyebrow_uk',
            field=models.CharField(default='Про нього', max_length=100, null=True, verbose_name='Життя — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_photos_eyebrow_en',
            field=models.CharField(default='Фото до історії', max_length=100, null=True, verbose_name='Життя — Фото: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_photos_eyebrow_uk',
            field=models.CharField(default='Фото до історії', max_length=100, null=True, verbose_name='Життя — Фото: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_photos_title_en',
            field=models.CharField(default='Роки, що залишилися у світлинах', max_length=200, null=True, verbose_name='Життя — Фото: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_photos_title_uk',
            field=models.CharField(default='Роки, що залишилися у світлинах', max_length=200, null=True, verbose_name='Життя — Фото: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_description_en',
            field=models.TextField(default='До публікації додаються лише події з підтвердженими датами та формулюваннями.', null=True, verbose_name='Життя — Хронологія: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_description_uk',
            field=models.TextField(default='До публікації додаються лише події з підтвердженими датами та формулюваннями.', null=True, verbose_name='Життя — Хронологія: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_empty_text_en',
            field=models.TextField(default='Підтверджені події з’являться тут після додавання через адміністративну панель.', null=True, verbose_name='Життя — Хронологія: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_empty_text_uk',
            field=models.TextField(default='Підтверджені події з’являться тут після додавання через адміністративну панель.', null=True, verbose_name='Життя — Хронологія: текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_empty_title_en',
            field=models.CharField(default='Хронологія ще наповнюється', max_length=200, null=True, verbose_name='Життя — Хронологія: заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_empty_title_uk',
            field=models.CharField(default='Хронологія ще наповнюється', max_length=200, null=True, verbose_name='Життя — Хронологія: заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_eyebrow_en',
            field=models.CharField(default='Хронологія', max_length=100, null=True, verbose_name='Життя — Хронологія: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_eyebrow_uk',
            field=models.CharField(default='Хронологія', max_length=100, null=True, verbose_name='Життя — Хронологія: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_title_en',
            field=models.CharField(default='Ключові події', max_length=200, null=True, verbose_name='Життя — Хронологія: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_timeline_title_uk',
            field=models.CharField(default='Ключові події', max_length=200, null=True, verbose_name='Життя — Хронологія: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_title_en',
            field=models.CharField(default='Життя', max_length=100, null=True, verbose_name='Назва розділу «Життя»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='life_title_uk',
            field=models.CharField(default='Життя', max_length=100, null=True, verbose_name='Назва розділу «Життя»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_empty_text_en',
            field=models.TextField(default='Перевірені публікації та офіційні джерела з’являться тут пізніше.', null=True, verbose_name='Матеріали — текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_empty_text_uk',
            field=models.TextField(default='Перевірені публікації та офіційні джерела з’являться тут пізніше.', null=True, verbose_name='Матеріали — текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_empty_title_en',
            field=models.CharField(default='Матеріалів поки немає', max_length=200, null=True, verbose_name='Матеріали — заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_empty_title_uk',
            field=models.CharField(default='Матеріалів поки немає', max_length=200, null=True, verbose_name='Матеріали — заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_hero_description_en',
            field=models.TextField(default='Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.', null=True, verbose_name='Матеріали — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_hero_description_uk',
            field=models.TextField(default='Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.', null=True, verbose_name='Матеріали — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_hero_eyebrow_en',
            field=models.CharField(default='Зовнішні джерела', max_length=100, null=True, verbose_name='Матеріали — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_hero_eyebrow_uk',
            field=models.CharField(default='Зовнішні джерела', max_length=100, null=True, verbose_name='Матеріали — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_section_title_en',
            field=models.CharField(default='Матеріали', max_length=200, null=True, verbose_name='Матеріали — заголовок розділу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_section_title_uk',
            field=models.CharField(default='Матеріали', max_length=200, null=True, verbose_name='Матеріали — заголовок розділу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_title_en',
            field=models.CharField(default='Посилання', max_length=100, null=True, verbose_name='Назва розділу «Посилання»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_title_uk',
            field=models.CharField(default='Посилання', max_length=100, null=True, verbose_name='Назва розділу «Посилання»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_verification_note_en',
            field=models.TextField(default='Перевірка посилань рекомендована 1–2 рази на рік.', null=True, verbose_name='Матеріали — примітка про перевірку посилань'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_verification_note_uk',
            field=models.TextField(default='Перевірка посилань рекомендована 1–2 рази на рік.', null=True, verbose_name='Матеріали — примітка про перевірку посилань'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_empty_text_en',
            field=models.TextField(default='Після перевірки модератором опубліковані спогади з’являться тут.', null=True, verbose_name='Спогади — текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_empty_text_uk',
            field=models.TextField(default='Після перевірки модератором опубліковані спогади з’являться тут.', null=True, verbose_name='Спогади — текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_empty_title_en',
            field=models.CharField(default='Спогадів поки немає', max_length=200, null=True, verbose_name='Спогади — заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_empty_title_uk',
            field=models.CharField(default='Спогадів поки немає', max_length=200, null=True, verbose_name='Спогади — заголовок порожнього стану'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_hero_description_en',
            field=models.TextField(default='Слова родини, побратимів, друзів і однокласників.', null=True, verbose_name='Спогади — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_hero_description_uk',
            field=models.TextField(default='Слова родини, побратимів, друзів і однокласників.', null=True, verbose_name='Спогади — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_hero_eyebrow_en',
            field=models.CharField(default='Слова близьких', max_length=100, null=True, verbose_name='Спогади — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_hero_eyebrow_uk',
            field=models.CharField(default='Слова близьких', max_length=100, null=True, verbose_name='Спогади — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderation_label_en',
            field=models.CharField(default='Модерація', max_length=100, null=True, verbose_name='Спогади — блок модерації: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderation_label_uk',
            field=models.CharField(default='Модерація', max_length=100, null=True, verbose_name='Спогади — блок модерації: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderation_note_en',
            field=models.TextField(default='Кожен текст публікується лише після ручної модерації.', null=True, verbose_name='Спогади — примітка про модерацію'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderation_note_uk',
            field=models.TextField(default='Кожен текст публікується лише після ручної модерації.', null=True, verbose_name='Спогади — примітка про модерацію'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderator_text_en',
            field=models.CharField(default='Відповідальна особа від родини', max_length=200, null=True, verbose_name='Спогади — блок модерації: відповідальна особа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_moderator_text_uk',
            field=models.CharField(default='Відповідальна особа від родини', max_length=200, null=True, verbose_name='Спогади — блок модерації: відповідальна особа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_description_en',
            field=models.TextField(default='Кожне повідомлення потрапляє на ручну модерацію й не з’являється на сайті автоматично.', null=True, verbose_name='Спогади — форма: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_description_uk',
            field=models.TextField(default='Кожне повідомлення потрапляє на ручну модерацію й не з’являється на сайті автоматично.', null=True, verbose_name='Спогади — форма: опис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_eyebrow_en',
            field=models.CharField(default='Поділитися спогадом', max_length=100, null=True, verbose_name='Спогади — форма: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_eyebrow_uk',
            field=models.CharField(default='Поділитися спогадом', max_length=100, null=True, verbose_name='Спогади — форма: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_title_en',
            field=models.CharField(default='Залиште кілька слів', max_length=200, null=True, verbose_name='Спогади — форма: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_title_uk',
            field=models.CharField(default='Залиште кілька слів', max_length=200, null=True, verbose_name='Спогади — форма: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_title_en',
            field=models.CharField(default='Спогади', max_length=100, null=True, verbose_name='Назва розділу «Спогади»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_title_uk',
            field=models.CharField(default='Спогади', max_length=100, null=True, verbose_name='Назва розділу «Спогади»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_category_empty_text_en',
            field=models.CharField(default='У цій категорії поки немає фотографій.', max_length=250, null=True, verbose_name='Фото — текст порожньої категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_category_empty_text_uk',
            field=models.CharField(default='У цій категорії поки немає фотографій.', max_length=250, null=True, verbose_name='Фото — текст порожньої категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_empty_text_en',
            field=models.TextField(default='Перевірені родиною фотографії з’являться тут після публікації.', null=True, verbose_name='Фото — текст порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_empty_text_uk',
            field=models.TextField(default='Перевірені родиною фотографії з’являться тут після публікації.', null=True, verbose_name='Фото — текст порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_empty_title_en',
            field=models.CharField(default='Фотоархів ще наповнюється', max_length=200, null=True, verbose_name='Фото — заголовок порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_empty_title_uk',
            field=models.CharField(default='Фотоархів ще наповнюється', max_length=200, null=True, verbose_name='Фото — заголовок порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_hero_description_en',
            field=models.TextField(default='Основний архів світлин, згрупований за періодами життя.', null=True, verbose_name='Фото — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_hero_description_uk',
            field=models.TextField(default='Основний архів світлин, згрупований за періодами життя.', null=True, verbose_name='Фото — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_hero_title_en',
            field=models.CharField(default='Фотоархів', max_length=200, null=True, verbose_name='Фото — заголовок сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_hero_title_uk',
            field=models.CharField(default='Фотоархів', max_length=200, null=True, verbose_name='Фото — заголовок сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_title_en',
            field=models.CharField(default='Фото', max_length=100, null=True, verbose_name='Назва розділу «Фото»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_title_uk',
            field=models.CharField(default='Фото', max_length=100, null=True, verbose_name='Назва розділу «Фото»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_verification_note_en',
            field=models.TextField(default='Кожне фото публікується лише після перевірки.', null=True, verbose_name='Фото — примітка про перевірку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_verification_note_uk',
            field=models.TextField(default='Кожне фото публікується лише після перевірки.', null=True, verbose_name='Фото — примітка про перевірку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_award_title_en',
            field=models.CharField(default='Нагорода', max_length=200, null=True, verbose_name='Подвиг і служба — заголовок блоку нагороди'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_award_title_uk',
            field=models.CharField(default='Нагорода', max_length=200, null=True, verbose_name='Подвиг і служба — заголовок блоку нагороди'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_eyebrow_en',
            field=models.CharField(default='Перед публікацією', max_length=100, null=True, verbose_name='Подвиг і служба — Перевірка: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_eyebrow_uk',
            field=models.CharField(default='Перед публікацією', max_length=100, null=True, verbose_name='Подвиг і служба — Перевірка: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_1_en',
            field=models.CharField(default='Текст погоджено з частиною або пресслужбою.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_1_uk',
            field=models.CharField(default='Текст погоджено з частиною або пресслужбою.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_2_en',
            field=models.CharField(default='Дата й номер Указу звірені з офіційним джерелом.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_2_uk',
            field=models.CharField(default='Дата й номер Указу звірені з офіційним джерелом.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_3_en',
            field=models.CharField(default='Немає координат, тактики, чисельності чи заборонених деталей.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_3_uk',
            field=models.CharField(default='Немає координат, тактики, чисельності чи заборонених деталей.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_4_en',
            field=models.CharField(default='Формулювання схвалені родиною.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_item_4_uk',
            field=models.CharField(default='Формулювання схвалені родиною.', max_length=300, null=True, verbose_name='Подвиг і служба — Перевірка: пункт 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_title_en',
            field=models.CharField(default='Перевірка фактів і безпеки', max_length=200, null=True, verbose_name='Подвиг і служба — Перевірка: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_checklist_title_uk',
            field=models.CharField(default='Перевірка фактів і безпеки', max_length=200, null=True, verbose_name='Подвиг і служба — Перевірка: заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_decree_link_text_en',
            field=models.CharField(default='Читати повний текст Указу', max_length=200, null=True, verbose_name='Подвиг і служба — текст посилання на Указ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_decree_link_text_uk',
            field=models.CharField(default='Читати повний текст Указу', max_length=200, null=True, verbose_name='Подвиг і служба — текст посилання на Указ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_editorial_label_en',
            field=models.CharField(default='Редакційна позначка', max_length=150, null=True, verbose_name='Подвиг і служба — редакційна позначка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_editorial_label_uk',
            field=models.CharField(default='Редакційна позначка', max_length=150, null=True, verbose_name='Подвиг і служба — редакційна позначка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_empty_text_en',
            field=models.TextField(default='Інформація для цього розділу ще не додана.', null=True, verbose_name='Подвиг і служба — текст, якщо даних немає'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_empty_text_uk',
            field=models.TextField(default='Інформація для цього розділу ще не додана.', null=True, verbose_name='Подвиг і служба — текст, якщо даних немає'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_safety_eyebrow_en',
            field=models.CharField(default='Безпека публікації', max_length=100, null=True, verbose_name='Подвиг і служба — Безпека: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_safety_eyebrow_uk',
            field=models.CharField(default='Безпека публікації', max_length=100, null=True, verbose_name='Подвиг і служба — Безпека: надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_section_title_en',
            field=models.CharField(default='Опис служби', max_length=200, null=True, verbose_name='Подвиг і служба — заголовок блоку служби'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_section_title_uk',
            field=models.CharField(default='Опис служби', max_length=200, null=True, verbose_name='Подвиг і служба — заголовок блоку служби'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_title_en',
            field=models.CharField(default='Подвиг і служба', max_length=100, null=True, verbose_name='Назва розділу «Подвиг і служба»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_title_uk',
            field=models.CharField(default='Подвиг і служба', max_length=100, null=True, verbose_name='Назва розділу «Подвиг і служба»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва в шапці'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва в шапці'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_en',
            field=models.CharField(default='Memorial', max_length=200, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_uk',
            field=models.CharField(default='Memorial', max_length=200, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Підзаголовок у шапці'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Підзаголовок у шапці'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_accessibility_label_en',
            field=models.CharField(default='Доступність:', max_length=100, null=True, verbose_name='Відео — заголовок примітки про доступність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_accessibility_label_uk',
            field=models.CharField(default='Доступність:', max_length=100, null=True, verbose_name='Відео — заголовок примітки про доступність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_accessibility_text_en',
            field=models.TextField(default='за можливості до відео додається текстовий опис або розшифровка.', null=True, verbose_name='Відео — текст примітки про доступність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_accessibility_text_uk',
            field=models.TextField(default='за можливості до відео додається текстовий опис або розшифровка.', null=True, verbose_name='Відео — текст примітки про доступність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_admin_note_en',
            field=models.TextField(default='Усі матеріали додаються та публікуються тільки через адміністративну панель.', null=True, verbose_name='Відео — примітка про публікацію'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_admin_note_uk',
            field=models.TextField(default='Усі матеріали додаються та публікуються тільки через адміністративну панель.', null=True, verbose_name='Відео — примітка про публікацію'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_all_records_label_en',
            field=models.CharField(default='Усі записи', max_length=100, null=True, verbose_name='Відео — надзаголовок архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_all_records_label_uk',
            field=models.CharField(default='Усі записи', max_length=100, null=True, verbose_name='Відео — надзаголовок архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_archive_title_en',
            field=models.CharField(default='Відеоархів', max_length=200, null=True, verbose_name='Відео — заголовок архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_archive_title_uk',
            field=models.CharField(default='Відеоархів', max_length=200, null=True, verbose_name='Відео — заголовок архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_empty_text_en',
            field=models.TextField(default='Перевірені відеоматеріали з’являться тут після публікації адміністратором.', null=True, verbose_name='Відео — текст порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_empty_text_uk',
            field=models.TextField(default='Перевірені відеоматеріали з’являться тут після публікації адміністратором.', null=True, verbose_name='Відео — текст порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_empty_title_en',
            field=models.CharField(default='Відеоархів ще наповнюється', max_length=200, null=True, verbose_name='Відео — заголовок порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_empty_title_uk',
            field=models.CharField(default='Відеоархів ще наповнюється', max_length=200, null=True, verbose_name='Відео — заголовок порожнього архіву'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_featured_label_en',
            field=models.CharField(default='Рекомендоване відео', max_length=150, null=True, verbose_name='Відео — підпис рекомендованого відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_featured_label_uk',
            field=models.CharField(default='Рекомендоване відео', max_length=150, null=True, verbose_name='Відео — підпис рекомендованого відео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_hero_description_en',
            field=models.TextField(default='Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.', null=True, verbose_name='Відео — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_hero_description_uk',
            field=models.TextField(default='Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.', null=True, verbose_name='Відео — опис сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_hero_eyebrow_en',
            field=models.CharField(default='Архівні записи', max_length=100, null=True, verbose_name='Відео — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_hero_eyebrow_uk',
            field=models.CharField(default='Архівні записи', max_length=100, null=True, verbose_name='Відео — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_title_en',
            field=models.CharField(default='Відео', max_length=100, null=True, verbose_name='Назва розділу «Відео»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_title_uk',
            field=models.CharField(default='Відео', max_length=100, null=True, verbose_name='Назва розділу «Відео»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_transcript_label_en',
            field=models.CharField(default='Текстовий опис відео', max_length=150, null=True, verbose_name='Відео — заголовок текстового опису'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_transcript_label_uk',
            field=models.CharField(default='Текстовий опис відео', max_length=150, null=True, verbose_name='Відео — заголовок текстового опису'),
        ),
    ]
