# Generated by Django 6.0.7 on 2026-09-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_copyright_holder_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_empty_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_empty_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_empty_text_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_empty_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_empty_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_empty_title_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_hero_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_hero_description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_hero_description_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_hero_eyebrow',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_hero_eyebrow_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_hero_eyebrow_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_section_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_section_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_section_title_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_title_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_verification_note',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_verification_note_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='media_verification_note_uk',
        ),
    ]
