# Generated by Django 6.0.7 on 2026-09-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_sitesettings_life_empty_biography_text_and_more'),
        ("pages", "0013_seed_photopage_from_sitesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_category_empty_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_category_empty_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_category_empty_text_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_empty_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_empty_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_empty_text_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_empty_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_empty_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_empty_title_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_hero_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_hero_description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_hero_description_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_hero_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_hero_title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_hero_title_uk',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_verification_note',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_verification_note_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='photos_verification_note_uk',
        ),
    ]
