# Generated by Django 6.0.7 on 2026-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_sitesettings_videos_accessibility_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='memories_error_message',
            field=models.TextField(default='Щось пішло не так. Перевірте дані у формі та спробуйте ще раз.', help_text='Також показується при проблемах зі з’єднанням. Введені дані зберігаються у формі.', verbose_name='Спогади — повідомлення про помилку надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_error_message_en',
            field=models.TextField(default='Щось пішло не так. Перевірте дані у формі та спробуйте ще раз.', help_text='Також показується при проблемах зі з’єднанням. Введені дані зберігаються у формі.', null=True, verbose_name='Спогади — повідомлення про помилку надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_error_message_uk',
            field=models.TextField(default='Щось пішло не так. Перевірте дані у формі та спробуйте ще раз.', help_text='Також показується при проблемах зі з’єднанням. Введені дані зберігаються у формі.', null=True, verbose_name='Спогади — повідомлення про помилку надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_rate_limit_message',
            field=models.TextField(default='Ви надіслали кілька спогадів за короткий час. Спробуйте, будь ласка, пізніше.', verbose_name='Спогади — повідомлення про ліміт надсилань'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_rate_limit_message_en',
            field=models.TextField(default='Ви надіслали кілька спогадів за короткий час. Спробуйте, будь ласка, пізніше.', null=True, verbose_name='Спогади — повідомлення про ліміт надсилань'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_rate_limit_message_uk',
            field=models.TextField(default='Ви надіслали кілька спогадів за короткий час. Спробуйте, будь ласка, пізніше.', null=True, verbose_name='Спогади — повідомлення про ліміт надсилань'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_button_label',
            field=models.CharField(default='Надіслати на модерацію', max_length=200, verbose_name='Спогади — форма: текст кнопки надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_button_label_en',
            field=models.CharField(default='Надіслати на модерацію', max_length=200, null=True, verbose_name='Спогади — форма: текст кнопки надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_submit_button_label_uk',
            field=models.CharField(default='Надіслати на модерацію', max_length=200, null=True, verbose_name='Спогади — форма: текст кнопки надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_success_message',
            field=models.TextField(default='Дякуємо. Ваш спогад надіслано на модерацію.', verbose_name='Спогади — повідомлення про успішне надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_success_message_en',
            field=models.TextField(default='Дякуємо. Ваш спогад надіслано на модерацію.', null=True, verbose_name='Спогади — повідомлення про успішне надсилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_success_message_uk',
            field=models.TextField(default='Дякуємо. Ваш спогад надіслано на модерацію.', null=True, verbose_name='Спогади — повідомлення про успішне надсилання'),
        ),
    ]
