# Generated by Django 6.0.7 on 2026-09-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_memories_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='demo_text',
            field=models.TextField(default='Усі персональні дані та матеріали умовні й мають бути замінені після перевірки родиною.', verbose_name='Демо — пояснення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_text_en',
            field=models.TextField(default='Усі персональні дані та матеріали умовні й мають бути замінені після перевірки родиною.', null=True, verbose_name='Демо — пояснення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_text_uk',
            field=models.TextField(default='Усі персональні дані та матеріали умовні й мають бути замінені після перевірки родиною.', null=True, verbose_name='Демо — пояснення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_title',
            field=models.TextField(default='Демонстраційний макет.', verbose_name='Демо — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_title_en',
            field=models.TextField(default='Демонстраційний макет.', null=True, verbose_name='Демо — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_title_uk',
            field=models.TextField(default='Демонстраційний макет.', null=True, verbose_name='Демо — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_dedication',
            field=models.TextField(default='Сторінка розроблена в світлу пам’ять Назара Боровицького', verbose_name='Футер — пам’ятний напис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_dedication_en',
            field=models.TextField(default='Сторінка розроблена в світлу пам’ять Назара Боровицького', null=True, verbose_name='Футер — пам’ятний напис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_dedication_uk',
            field=models.TextField(default='Сторінка розроблена в світлу пам’ять Назара Боровицького', null=True, verbose_name='Футер — пам’ятний напис'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='language_label',
            field=models.TextField(default='Мова', verbose_name='Хедер — мова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='language_label_en',
            field=models.TextField(default='Мова', null=True, verbose_name='Хедер — мова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='language_label_uk',
            field=models.TextField(default='Мова', null=True, verbose_name='Хедер — мова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_category_label',
            field=models.TextField(default='Ким ви були знайомі', verbose_name='Спогади — підпис категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_category_label_en',
            field=models.TextField(default='Ким ви були знайомі', null=True, verbose_name='Спогади — підпис категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_category_label_uk',
            field=models.TextField(default='Ким ви були знайомі', null=True, verbose_name='Спогади — підпис категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_category_placeholder',
            field=models.TextField(default='Оберіть варіант', verbose_name='Спогади — порожня категорія'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_category_placeholder_en',
            field=models.TextField(default='Оберіть варіант', null=True, verbose_name='Спогади — порожня категорія'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_category_placeholder_uk',
            field=models.TextField(default='Оберіть варіант', null=True, verbose_name='Спогади — порожня категорія'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_characters_label',
            field=models.TextField(default='символів', verbose_name='Спогади — одиниця лічильника'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_characters_label_en',
            field=models.TextField(default='символів', null=True, verbose_name='Спогади — одиниця лічильника'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_characters_label_uk',
            field=models.TextField(default='символів', null=True, verbose_name='Спогади — одиниця лічильника'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_close_dialog_label',
            field=models.TextField(default='Закрити спогад', verbose_name='Спогади — закриття діалогу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_close_dialog_label_en',
            field=models.TextField(default='Закрити спогад', null=True, verbose_name='Спогади — закриття діалогу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_close_dialog_label_uk',
            field=models.TextField(default='Закрити спогад', null=True, verbose_name='Спогади — закриття діалогу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_close_label',
            field=models.TextField(default='Закрити', verbose_name='Спогади — закриття'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_close_label_en',
            field=models.TextField(default='Закрити', null=True, verbose_name='Спогади — закриття'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_close_label_uk',
            field=models.TextField(default='Закрити', null=True, verbose_name='Спогади — закриття'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_consent_label',
            field=models.TextField(default='Погоджуюся на публікацію після перевірки модератором.', verbose_name='Спогади — згода'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_consent_label_en',
            field=models.TextField(default='Погоджуюся на публікацію після перевірки модератором.', null=True, verbose_name='Спогади — згода'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_consent_label_uk',
            field=models.TextField(default='Погоджуюся на публікацію після перевірки модератором.', null=True, verbose_name='Спогади — згода'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_escape_label',
            field=models.TextField(default='Esc — закрити', verbose_name='Спогади — підказка клавіші'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_escape_label_en',
            field=models.TextField(default='Esc — закрити', null=True, verbose_name='Спогади — підказка клавіші'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_escape_label_uk',
            field=models.TextField(default='Esc — закрити', null=True, verbose_name='Спогади — підказка клавіші'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_invalid_error',
            field=models.TextField(default='Перевірте це поле.', verbose_name='Спогади — помилка поля'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_invalid_error_en',
            field=models.TextField(default='Перевірте це поле.', null=True, verbose_name='Спогади — помилка поля'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_invalid_error_uk',
            field=models.TextField(default='Перевірте це поле.', null=True, verbose_name='Спогади — помилка поля'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_limit_message',
            field=models.TextField(default='Досягнуто ліміт в 15 000 символів. Надішліть цей спогад, а продовження — ще однією формою.', verbose_name='Спогади — ліміт тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_limit_message_en',
            field=models.TextField(default='Досягнуто ліміт в 15 000 символів. Надішліть цей спогад, а продовження — ще однією формою.', null=True, verbose_name='Спогади — ліміт тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_limit_message_uk',
            field=models.TextField(default='Досягнуто ліміт в 15 000 символів. Надішліть цей спогад, а продовження — ще однією формою.', null=True, verbose_name='Спогади — ліміт тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_more_label',
            field=models.TextField(default='Дивитись більше', verbose_name='Спогади — кнопка розгортання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_more_label_en',
            field=models.TextField(default='Дивитись більше', null=True, verbose_name='Спогади — кнопка розгортання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_more_label_uk',
            field=models.TextField(default='Дивитись більше', null=True, verbose_name='Спогади — кнопка розгортання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_error',
            field=models.TextField(default='Вкажіть ім’я або підпис щонайменше з двох символів.', verbose_name='Спогади — коротке ім’я'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_error_en',
            field=models.TextField(default='Вкажіть ім’я або підпис щонайменше з двох символів.', null=True, verbose_name='Спогади — коротке ім’я'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_error_uk',
            field=models.TextField(default='Вкажіть ім’я або підпис щонайменше з двох символів.', null=True, verbose_name='Спогади — коротке ім’я'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_label',
            field=models.TextField(default='Ім’я або підпис', verbose_name='Спогади — підпис поля імені'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_label_en',
            field=models.TextField(default='Ім’я або підпис', null=True, verbose_name='Спогади — підпис поля імені'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_label_uk',
            field=models.TextField(default='Ім’я або підпис', null=True, verbose_name='Спогади — підпис поля імені'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_placeholder',
            field=models.TextField(default='Наприклад: Іван або позивний «Сокіл»', verbose_name='Спогади — приклад імені'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_placeholder_en',
            field=models.TextField(default='Наприклад: Іван або позивний «Сокіл»', null=True, verbose_name='Спогади — приклад імені'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_name_placeholder_uk',
            field=models.TextField(default='Наприклад: Іван або позивний «Сокіл»', null=True, verbose_name='Спогади — приклад імені'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_required_error',
            field=models.TextField(default='Це поле обов’язкове.', verbose_name='Спогади — обов’язкове поле'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_required_error_en',
            field=models.TextField(default='Це поле обов’язкове.', null=True, verbose_name='Спогади — обов’язкове поле'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_required_error_uk',
            field=models.TextField(default='Це поле обов’язкове.', null=True, verbose_name='Спогади — обов’язкове поле'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_error',
            field=models.TextField(default='Спогад має містити щонайменше 10 символів.', verbose_name='Спогади — короткий текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_error_en',
            field=models.TextField(default='Спогад має містити щонайменше 10 символів.', null=True, verbose_name='Спогади — короткий текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_error_uk',
            field=models.TextField(default='Спогад має містити щонайменше 10 символів.', null=True, verbose_name='Спогади — короткий текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_hint',
            field=models.TextField(default='Довгі спогади у стрічці показуються скорочено — повний текст відкривається кнопкою «Дивитись більше».', verbose_name='Спогади — пояснення скорочення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_hint_en',
            field=models.TextField(default='Довгі спогади у стрічці показуються скорочено — повний текст відкривається кнопкою «Дивитись більше».', null=True, verbose_name='Спогади — пояснення скорочення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_hint_uk',
            field=models.TextField(default='Довгі спогади у стрічці показуються скорочено — повний текст відкривається кнопкою «Дивитись більше».', null=True, verbose_name='Спогади — пояснення скорочення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_label',
            field=models.TextField(default='Текст спогаду', verbose_name='Спогади — підпис тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_label_en',
            field=models.TextField(default='Текст спогаду', null=True, verbose_name='Спогади — підпис тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_label_uk',
            field=models.TextField(default='Текст спогаду', null=True, verbose_name='Спогади — підпис тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_placeholder',
            field=models.TextField(default='Напишіть спогад', verbose_name='Спогади — підказка тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_placeholder_en',
            field=models.TextField(default='Напишіть спогад', null=True, verbose_name='Спогади — підказка тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='memories_text_placeholder_uk',
            field=models.TextField(default='Напишіть спогад', null=True, verbose_name='Спогади — підказка тексту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_language_label',
            field=models.TextField(default='МОВА / LANGUAGE', verbose_name='Хедер — мова в мобільному меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_language_label_en',
            field=models.TextField(default='МОВА / LANGUAGE', null=True, verbose_name='Хедер — мова в мобільному меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_language_label_uk',
            field=models.TextField(default='МОВА / LANGUAGE', null=True, verbose_name='Хедер — мова в мобільному меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_family',
            field=models.TextField(default='Сім’я та дитинство', verbose_name='Фото — назва категорії «Сім’я та дитинство»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_family_en',
            field=models.TextField(default='Сім’я та дитинство', null=True, verbose_name='Фото — назва категорії «Сім’я та дитинство»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_family_uk',
            field=models.TextField(default='Сім’я та дитинство', null=True, verbose_name='Фото — назва категорії «Сім’я та дитинство»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_memory',
            field=models.TextField(default='Вшанування', verbose_name='Фото — назва категорії «Вшанування»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_memory_en',
            field=models.TextField(default='Вшанування', null=True, verbose_name='Фото — назва категорії «Вшанування»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_memory_uk',
            field=models.TextField(default='Вшанування', null=True, verbose_name='Фото — назва категорії «Вшанування»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_service',
            field=models.TextField(default='Служба та побратими', verbose_name='Фото — назва категорії «Служба та побратими»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_service_en',
            field=models.TextField(default='Служба та побратими', null=True, verbose_name='Фото — назва категорії «Служба та побратими»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_service_uk',
            field=models.TextField(default='Служба та побратими', null=True, verbose_name='Фото — назва категорії «Служба та побратими»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_study',
            field=models.TextField(default='Навчання', verbose_name='Фото — назва категорії «Навчання»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_study_en',
            field=models.TextField(default='Навчання', null=True, verbose_name='Фото — назва категорії «Навчання»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_category_study_uk',
            field=models.TextField(default='Навчання', null=True, verbose_name='Фото — назва категорії «Навчання»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_all_label',
            field=models.TextField(default='Усі фото', verbose_name='Фото — всі категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_all_label_en',
            field=models.TextField(default='Усі фото', null=True, verbose_name='Фото — всі категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_all_label_uk',
            field=models.TextField(default='Усі фото', null=True, verbose_name='Фото — всі категорії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_family',
            field=models.TextField(default='Сімейний архів', verbose_name='Відео — назва категорії «Сімейний архів»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_family_en',
            field=models.TextField(default='Сімейний архів', null=True, verbose_name='Відео — назва категорії «Сімейний архів»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_family_uk',
            field=models.TextField(default='Сімейний архів', null=True, verbose_name='Відео — назва категорії «Сімейний архів»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_interview',
            field=models.TextField(default='Інтерв’ю', verbose_name='Відео — назва категорії «Інтерв’ю»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_interview_en',
            field=models.TextField(default='Інтерв’ю', null=True, verbose_name='Відео — назва категорії «Інтерв’ю»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_interview_uk',
            field=models.TextField(default='Інтерв’ю', null=True, verbose_name='Відео — назва категорії «Інтерв’ю»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_media',
            field=models.TextField(default='Матеріали ЗМІ', verbose_name='Відео — назва категорії «Матеріали ЗМІ»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_media_en',
            field=models.TextField(default='Матеріали ЗМІ', null=True, verbose_name='Відео — назва категорії «Матеріали ЗМІ»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_media_uk',
            field=models.TextField(default='Матеріали ЗМІ', null=True, verbose_name='Відео — назва категорії «Матеріали ЗМІ»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_memory',
            field=models.TextField(default='Вшанування', verbose_name='Відео — назва категорії «Вшанування»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_memory_en',
            field=models.TextField(default='Вшанування', null=True, verbose_name='Відео — назва категорії «Вшанування»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_memory_uk',
            field=models.TextField(default='Вшанування', null=True, verbose_name='Відео — назва категорії «Вшанування»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_other',
            field=models.TextField(default='Інше', verbose_name='Відео — назва категорії «Інше»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_other_en',
            field=models.TextField(default='Інше', null=True, verbose_name='Відео — назва категорії «Інше»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_other_uk',
            field=models.TextField(default='Інше', null=True, verbose_name='Відео — назва категорії «Інше»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_service',
            field=models.TextField(default='Служба', verbose_name='Відео — назва категорії «Служба»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_service_en',
            field=models.TextField(default='Служба', null=True, verbose_name='Відео — назва категорії «Служба»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_category_service_uk',
            field=models.TextField(default='Служба', null=True, verbose_name='Відео — назва категорії «Служба»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_category_label',
            field=models.TextField(default='Категорія', verbose_name='Відео — категорія'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_category_label_en',
            field=models.TextField(default='Категорія', null=True, verbose_name='Відео — категорія'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_category_label_uk',
            field=models.TextField(default='Категорія', null=True, verbose_name='Відео — категорія'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_date_label',
            field=models.TextField(default='Дата запису', verbose_name='Відео — дата'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_date_label_en',
            field=models.TextField(default='Дата запису', null=True, verbose_name='Відео — дата'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_date_label_uk',
            field=models.TextField(default='Дата запису', null=True, verbose_name='Відео — дата'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_duration_label',
            field=models.TextField(default='Тривалість', verbose_name='Відео — тривалість'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_duration_label_en',
            field=models.TextField(default='Тривалість', null=True, verbose_name='Відео — тривалість'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='videos_duration_label_uk',
            field=models.TextField(default='Тривалість', null=True, verbose_name='Відео — тривалість'),
        ),
    ]
