# Generated by Django 6.0.7 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=255, verbose_name="Джерело"),
                ),
                ("url", models.URLField(verbose_name="Посилання")),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата публікації"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Згадка в медіа",
                "verbose_name_plural": "Згадки в медіа",
                "ordering": ["order", "-published_date"],
            },
        ),
    ]
