# Generated by Django 6.0.7 on 2026-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamention',
            name='category',
            field=models.CharField(choices=[('official', 'Офіційне джерело'), ('press', 'ЗМІ')], default='press', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок матеріалу'),
        ),
        migrations.AlterField(
            model_name='mediamention',
            name='source_name',
            field=models.CharField(max_length=255, verbose_name='Назва джерела'),
        ),
    ]
