# Generated by Django 6.0.7 on 2026-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0002_mediamention_category_mediamention_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamention',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок матеріалу'),
        ),
    ]
