# Generated by Django 6.0.7 on 2026-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0003_alter_mediamention_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamention',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Рекомендовано вибрати лише один матеріал.', verbose_name='Показувати на головній'),
        ),
    ]
