# Generated by Django 6.0.7 on 2026-08-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0004_mediamention_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediamention',
            options={'ordering': ['order', '-published_date'], 'verbose_name': 'Публікація', 'verbose_name_plural': 'Публікації'},
        ),
    ]
