# Generated by Django 6.0.7 on 2026-09-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0005_alter_mediamention_options'),
        ('pages', '0002_serviceaward_servicequote'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamention',
            name='service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='pages.servicepage', verbose_name='Подвиг і служба'),
        ),
    ]
