# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0006_mediamention_service_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamention',
            name='source_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва джерела'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='source_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва джерела'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок матеріалу'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок матеріалу'),
        ),
    ]
