# Generated by Django 6.0.7 on 2026-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0008_attach_mentions_to_service_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamention',
            name='auto_preview_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media_mentions/previews/auto/', verbose_name='Автоматичне прев’ю'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='preview_fetched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Прев’ю отримано'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='preview_fetched_from',
            field=models.URLField(blank=True, editable=False, verbose_name='Джерело автоматичного прев’ю'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Необов’язково. Якщо завантажити зображення вручну, воно матиме пріоритет над автоматичним прев’ю.', null=True, upload_to='media_mentions/previews/manual/', verbose_name='Зображення прев’ю'),
        ),
    ]
