# Generated by Django 6.0.7 on 2026-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0009_mediamention_auto_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamention',
            name='preview_fetched_from',
            field=models.URLField(blank=True, editable=False, max_length=2048, verbose_name='Джерело автоматичного прев’ю'),
        ),
    ]
