# Generated by Django 6.0.7 on 2026-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_mentions', '0010_alter_mediamention_preview_fetched_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamention',
            name='preview_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Оптимізовані копії прев’ю'),
        ),
    ]
