# Generated by Django 6.0.7 on 2026-08-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Назва"),
                ),
                (
                    "embed_url",
                    models.URLField(verbose_name="Посилання (YouTube/Vimeo embed)"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="videos/",
                        verbose_name="Превʼю",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Відео",
                "verbose_name_plural": "Відео",
                "ordering": ["order", "id"],
            },
        ),
    ]
