# Generated by Django 6.0.7 on 2026-08-04 14:51

import django.utils.timezone
from django.db import migrations, models

import apps.videos.models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="embed_url",
        ),
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("family", "Сімейний архів"),
                    ("interview", "Інтерв’ю"),
                    ("service", "Служба"),
                    ("memory", "Вшанування"),
                    ("media", "Матеріали ЗМІ"),
                    ("other", "Інше"),
                ],
                default="other",
                max_length=20,
                verbose_name="Категорія",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Додано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Короткий опис"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: 03:42.",
                max_length=20,
                verbose_name="Тривалість",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="На сторінці бажано мати лише одне рекомендоване відео.",
                verbose_name="Рекомендоване відео",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Неопубліковане відео не відображається на сайті.",
                verbose_name="Опубліковано",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="recorded_at",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: 2022 або листопад 2023.",
                max_length=100,
                verbose_name="Дата або період запису",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="transcript",
            field=models.TextField(
                blank=True,
                help_text="Необов’язковий текстовий опис змісту відео.",
                verbose_name="Розшифровка або субтитри",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Дозволені формати: MP4, WebM або MOV. Максимальний розмір — 300 MB.",
                upload_to="videos/files/",
                validators=[
                    apps.videos.models.validate_video_extension,
                    apps.videos.models.validate_video_size,
                ],
                verbose_name="Відеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендоване співвідношення сторін — 16:9.",
                null=True,
                upload_to="videos/thumbnails/",
                verbose_name="Обкладинка",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
    ]
