# Generated by Django 6.0.7 on 2026-08-04 14:57

from django.db import migrations, models

import apps.videos.models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_remove_video_embed_url_video_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                help_text="Дозволені формати: MP4, WebM або MOV. Максимальний розмір — 300 MB.",
                upload_to="videos/files/",
                validators=[
                    apps.videos.models.validate_video_extension,
                    apps.videos.models.validate_video_size,
                ],
                verbose_name="Відеофайл",
            ),
        ),
    ]
