# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='video',
            name='recorded_at_en',
            field=models.CharField(blank=True, help_text='Наприклад: 2022 або листопад 2023.', max_length=100, null=True, verbose_name='Дата або період запису'),
        ),
        migrations.AddField(
            model_name='video',
            name='recorded_at_uk',
            field=models.CharField(blank=True, help_text='Наприклад: 2022 або листопад 2023.', max_length=100, null=True, verbose_name='Дата або період запису'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_en',
            field=models.TextField(blank=True, help_text='Необов’язковий текстовий опис змісту відео.', null=True, verbose_name='Розшифровка або субтитри'),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_uk',
            field=models.TextField(blank=True, help_text='Необов’язковий текстовий опис змісту відео.', null=True, verbose_name='Розшифровка або субтитри'),
        ),
    ]
