# Generated by Django 6.0.7 on 2026-09-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_description_en_video_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('family', 'Сімейний архів'), ('interview', 'Інтерв’ю'), ('service', 'Служба'), ('memory', 'Вшанування'), ('media', 'Матеріали ЗМІ'), ('other', 'Інше')], default='other', help_text='Допомагає класифікувати відео та показує його тип у відповідних блоках сайту.', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Рекомендованим може бути лише одне відео. Якщо вибрати інше, попереднє перестане бути рекомендованим.', verbose_name='Показувати як рекомендоване'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Якщо вимкнено, відео зберігається в адмінці, але не відображається на сайті.', verbose_name='Показувати відео на сайті'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Менше число — відео буде показане раніше.', verbose_name='Порядок відображення'),
        ),
    ]
