# Generated by Django 6.0.7 on 2026-09-18 10:46

import apps.videos.models
import apps.videos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(help_text='Дозволені формати: MP4, WebM або MOV. Максимальний розмір — 300 MB.', storage=apps.videos.storage.get_video_storage, upload_to='videos/files/', validators=[apps.videos.models.validate_video_extension, apps.videos.models.validate_video_size], verbose_name='Відеофайл'),
        ),
    ]
