# Generated by Django 6.0.7 on 2026-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Оптимізовані копії обкладинки'),
        ),
    ]
