# Generated by Django 6.0.7 on 2026-08-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255, verbose_name="Імʼя")),
                (
                    "author_role",
                    models.CharField(
                        blank=True,
                        help_text="Наприклад: «побратим, позивний «Сокіл»»",
                        max_length=255,
                        verbose_name="Хто автор",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=500, verbose_name="Текст спогаду"),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Лише один спогад варто позначати як featured",
                        verbose_name="Показувати на головній",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На модерації"),
                            ("approved", "Опубліковано"),
                            ("rejected", "Відхилено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
            ],
            options={
                "verbose_name": "Спогад",
                "verbose_name_plural": "Спогади",
                "ordering": ["-created_at"],
            },
        ),
    ]
