# Generated by Django 6.0.7 on 2026-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст спогаду'),
        ),
    ]
