# Generated by Django 6.0.7 on 2026-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_memory_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='text',
            field=models.TextField(max_length=15000, verbose_name='Текст спогаду'),
        ),
    ]
