# Generated by Django 6.0.7 on 2026-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_alter_memory_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='text_en',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст спогаду'),
        ),
        migrations.AddField(
            model_name='memory',
            name='text_uk',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст спогаду'),
        ),
    ]
