# Generated by Django 6.0.7 on 2026-09-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memory_text_en_memory_text_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія спогадів',
                'verbose_name_plural': 'Категорії спогадів',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memories', to='memories.memorycategory', verbose_name='Категорія'),
        ),
    ]
