# Generated by Django 6.0.7 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeoPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Головна"),
                            ("life", "Життя"),
                            ("service", "Подвиг і служба"),
                            ("photos", "Фото"),
                            ("videos", "Відео"),
                            ("media", "У ЗМІ"),
                            ("memories", "Спогади"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Сторінка",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="Meta description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG-зображення",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO сторінки",
                "verbose_name_plural": "SEO сторінок",
            },
        ),
    ]
