# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='description_en',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='description_uk',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
