# Generated by Django 6.0.7 on 2026-09-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seopage_description_en_seopage_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='page_key',
            field=models.CharField(choices=[('home', 'Головна'), ('life', 'Життя'), ('service', 'Подвиг і служба'), ('photos', 'Фото'), ('videos', 'Відео'), ('memories', 'Спогади')], max_length=20, unique=True, verbose_name='Сторінка'),
        ),
    ]
