# Generated by Django 6.0.7 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_label",
                    models.CharField(max_length=50, verbose_name="Дата / період"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок події"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="Опис"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Подія хронології",
                "verbose_name_plural": "Хронологія",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="biography",
            name="award_title",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: «Герой України»",
                max_length=255,
                verbose_name="Нагорода (коротко)",
            ),
        ),
        migrations.AddField(
            model_name="biography",
            name="intro_text",
            field=models.TextField(
                blank=True, verbose_name="Вступний текст на головній"
            ),
        ),
        migrations.AddField(
            model_name="biography",
            name="rank",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: «Старший лейтенант, командир взводу»",
                max_length=255,
                verbose_name="Звання / роль",
            ),
        ),
        migrations.AddField(
            model_name="biography",
            name="signature_quote",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Ключова цитата"
            ),
        ),
    ]
