# Generated by Django 6.0.7 on 2026-08-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_timelineevent_biography_award_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='biography',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='biography.biography', verbose_name='Життєпис'),
            preserve_default=False,
        ),
    ]
