# Generated by Django 6.0.7 on 2026-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_timelineevent_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='rank',
            field=models.CharField(blank=True, help_text='Наприклад: «Старший лейтенант, командир взводу»', max_length=255, verbose_name='Звання'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='signature_quote',
            field=models.CharField(blank=True, max_length=500, verbose_name='Головна цитата'),
        ),
    ]
