# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0004_alter_biography_rank_alter_biography_signature_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='award_title_en',
            field=models.CharField(blank=True, help_text='Наприклад: «Герой України»', max_length=255, null=True, verbose_name='Нагорода (коротко)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='award_title_uk',
            field=models.CharField(blank=True, help_text='Наприклад: «Герой України»', max_length=255, null=True, verbose_name='Нагорода (коротко)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ПІБ'),
        ),
        migrations.AddField(
            model_name='biography',
            name='full_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='ПІБ'),
        ),
        migrations.AddField(
            model_name='biography',
            name='full_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Повний життєпис'),
        ),
        migrations.AddField(
            model_name='biography',
            name='full_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Повний життєпис'),
        ),
        migrations.AddField(
            model_name='biography',
            name='intro_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Вступний текст на головній'),
        ),
        migrations.AddField(
            model_name='biography',
            name='intro_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Вступний текст на головній'),
        ),
        migrations.AddField(
            model_name='biography',
            name='rank_en',
            field=models.CharField(blank=True, help_text='Наприклад: «Старший лейтенант, командир взводу»', max_length=255, null=True, verbose_name='Звання'),
        ),
        migrations.AddField(
            model_name='biography',
            name='rank_uk',
            field=models.CharField(blank=True, help_text='Наприклад: «Старший лейтенант, командир взводу»', max_length=255, null=True, verbose_name='Звання'),
        ),
        migrations.AddField(
            model_name='biography',
            name='signature_quote_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Головна цитата'),
        ),
        migrations.AddField(
            model_name='biography',
            name='signature_quote_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Головна цитата'),
        ),
        migrations.AddField(
            model_name='biography',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис (для головної)'),
        ),
        migrations.AddField(
            model_name='biography',
            name='summary_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис (для головної)'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='date_label_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата / період'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='date_label_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата / період'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок події'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок події'),
        ),
    ]
