# Generated by Django 6.0.7 on 2026-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0005_biography_award_title_en_biography_award_title_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='portrait_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Оптимізовані копії портрета'),
        ),
    ]
