# Generated by Django 6.0.7 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/", verbose_name="Фото")),
                (
                    "caption",
                    models.CharField(blank=True, max_length=255, verbose_name="Підпис"),
                ),
                (
                    "layout_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Звичайний"),
                            ("span-tall", "Високий"),
                            ("span-wide", "Широкий"),
                        ],
                        max_length=20,
                        verbose_name="Розмір у сітці",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фотогалерея",
                "ordering": ["order", "id"],
            },
        ),
    ]
