# Generated by Django 6.0.7 on 2026-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Короткий опис для людей, які використовують екранні читачі.",
                max_length=255,
                verbose_name="Опис зображення",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="category",
            field=models.CharField(
                choices=[
                    ("family", "Сім’я та дитинство"),
                    ("study", "Навчання"),
                    ("service", "Служба та побратими"),
                    ("memory", "Вшанування"),
                ],
                default="family",
                max_length=20,
                verbose_name="Категорія",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Неопубліковане фото не відображається на сайті.",
                verbose_name="Опубліковано",
            ),
        ),
    ]
