# Generated by Django 6.0.7 on 2026-08-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_alt_text_photo_category_photo_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
