# Generated by Django 6.0.7 on 2026-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='layout_size',
            field=models.CharField(blank=True, choices=[('', 'Автоматично'), ('span-tall', 'Вертикальне 9:16'), ('span-wide', 'Горизонтальне 16:9')], max_length=20, verbose_name='Розмір у сітці'),
        ),
    ]
