# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_layout_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Короткий опис для людей, які використовують екранні читачі.', max_length=255, null=True, verbose_name='Опис зображення'),
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_text_uk',
            field=models.CharField(blank=True, help_text='Короткий опис для людей, які використовують екранні читачі.', max_length=255, null=True, verbose_name='Опис зображення'),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підпис'),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підпис'),
        ),
    ]
