# Generated by Django 6.0.7 on 2026-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_preview_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('family', 'Сім’я та дитинство'), ('study', 'Навчання'), ('service', 'Служба та побратими'), ('memory', 'Вшанування')], default='family', help_text='Визначає, у якій категорії фото буде показане на сторінці.', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Якщо вимкнено, фото зберігається в адмінці, але не відображається на сайті.', verbose_name='Показувати фото на сайті'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='layout_size',
            field=models.CharField(blank=True, choices=[('', 'Автоматично'), ('span-tall', 'Вертикальне 9:16'), ('span-wide', 'Горизонтальне 16:9')], help_text='Визначає форму прев’ю фото в галереї. У більшості випадків залишайте «Автоматично».', max_length=20, verbose_name='Формат у галереї'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Менше число — фото буде показане раніше.', verbose_name='Порядок відображення'),
        ),
    ]
