# Generated by Django 6.0.7 on 2026-09-17 19:51

import django.core.validators
from django.db import migrations, models


def copy_existing_focus(apps, schema_editor):
    Photo = apps.get_model("gallery", "Photo")
    Photo.objects.using(schema_editor.connection.alias).update(
        portrait_focus_x=models.F("preview_focus_x"),
        portrait_focus_y=models.F("preview_focus_y"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_photo_category_alter_photo_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='portrait_focus_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Фокус вертикального прев’ю по горизонталі'),
        ),
        migrations.AddField(
            model_name='photo',
            name='portrait_focus_y',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Фокус вертикального прев’ю по вертикалі'),
        ),
        migrations.RunPython(copy_existing_focus, migrations.RunPython.noop),
    ]
