# Generated by Django 6.0.7 on 2026-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photo_portrait_focus_x_photo_portrait_focus_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Оптимізовані копії'),
        ),
    ]
