# Generated by Django 6.0.7 on 2026-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Офіційно узгоджений розділ', max_length=150, verbose_name='Позначка над заголовком')),
                ('hero_title', models.CharField(default='Подвиг і служба', max_length=150, verbose_name='Заголовок сторінки')),
                ('hero_description', models.TextField(blank=True, verbose_name='Опис у першому екрані')),
                ('publication_status', models.CharField(choices=[('draft', 'Чернетка'), ('needs_approval', 'Потрібне погодження'), ('approved', 'Погоджено до публікації')], default='needs_approval', max_length=30, verbose_name='Статус публікації')),
                ('service_intro', models.TextField(blank=True, verbose_name='Основний опис служби')),
                ('service_text', models.TextField(blank=True, verbose_name='Додатковий текст')),
                ('editorial_note', models.TextField(blank=True, verbose_name='Редакційна примітка')),
                ('award_title', models.CharField(blank=True, max_length=255, verbose_name='Назва нагороди')),
                ('award_subtitle', models.CharField(blank=True, help_text='Наприклад: Орден «Золота Зірка» (посмертно)', max_length=255, verbose_name='Уточнення про нагороду')),
                ('decree_date', models.DateField(blank=True, null=True, verbose_name='Дата указу')),
                ('decree_number', models.CharField(blank=True, max_length=100, verbose_name='Номер указу')),
                ('decree_source_name', models.CharField(blank=True, default='president.gov.ua', max_length=255, verbose_name='Назва офіційного джерела')),
                ('decree_url', models.URLField(blank=True, verbose_name='Посилання на текст указу')),
                ('is_published', models.BooleanField(default=False, help_text='Увімкніть після погодження матеріалів.', verbose_name='Показувати сторінку')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Подвиг і служба',
                'verbose_name_plural': 'Подвиг і служба',
            },
        ),
    ]
