# Generated by Django 6.0.7 on 2026-08-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва нагороди')),
                ('subtitle', models.CharField(blank=True, help_text='Наприклад: Орден «Золота Зірка» (посмертно)', max_length=255, verbose_name='Уточнення')),
                ('decree_date', models.DateField(blank=True, null=True, verbose_name='Дата указу')),
                ('decree_number', models.CharField(blank=True, max_length=100, verbose_name='Номер указу')),
                ('decree_source_name', models.CharField(blank=True, max_length=255, verbose_name='Назва офіційного джерела')),
                ('decree_url', models.URLField(blank=True, verbose_name='Посилання на текст указу')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='pages.servicepage', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Нагорода',
                'verbose_name_plural': 'Нагороди',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цитата')),
                ('context', models.CharField(blank=True, help_text='Наприклад: із розмови з побратимами', max_length=255, verbose_name='Контекст / підпис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='pages.servicepage', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитати',
                'ordering': ('order', 'id'),
            },
        ),
    ]
