# Generated by Django 6.0.7 on 2026-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_serviceaward_servicequote'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaward',
            name='decree_source_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва офіційного джерела'),
        ),
        migrations.AddField(
            model_name='serviceaward',
            name='decree_source_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва офіційного джерела'),
        ),
        migrations.AddField(
            model_name='serviceaward',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Наприклад: Орден «Золота Зірка» (посмертно)', max_length=255, null=True, verbose_name='Уточнення'),
        ),
        migrations.AddField(
            model_name='serviceaward',
            name='subtitle_uk',
            field=models.CharField(blank=True, help_text='Наприклад: Орден «Золота Зірка» (посмертно)', max_length=255, null=True, verbose_name='Уточнення'),
        ),
        migrations.AddField(
            model_name='serviceaward',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва нагороди'),
        ),
        migrations.AddField(
            model_name='serviceaward',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва нагороди'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_subtitle_en',
            field=models.CharField(blank=True, help_text='Наприклад: Орден «Золота Зірка» (посмертно)', max_length=255, null=True, verbose_name='Уточнення про нагороду'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_subtitle_uk',
            field=models.CharField(blank=True, help_text='Наприклад: Орден «Золота Зірка» (посмертно)', max_length=255, null=True, verbose_name='Уточнення про нагороду'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва нагороди'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва нагороди'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='decree_source_name_en',
            field=models.CharField(blank=True, default='president.gov.ua', max_length=255, null=True, verbose_name='Назва офіційного джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='decree_source_name_uk',
            field=models.CharField(blank=True, default='president.gov.ua', max_length=255, null=True, verbose_name='Назва офіційного джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='editorial_note_en',
            field=models.TextField(blank=True, null=True, verbose_name='Редакційна примітка'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='editorial_note_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Редакційна примітка'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис у першому екрані'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис у першому екрані'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_eyebrow_en',
            field=models.CharField(default='Офіційно узгоджений розділ', max_length=150, null=True, verbose_name='Позначка над заголовком'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_eyebrow_uk',
            field=models.CharField(default='Офіційно узгоджений розділ', max_length=150, null=True, verbose_name='Позначка над заголовком'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_title_en',
            field=models.CharField(default='Подвиг і служба', max_length=150, null=True, verbose_name='Заголовок сторінки'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_title_uk',
            field=models.CharField(default='Подвиг і служба', max_length=150, null=True, verbose_name='Заголовок сторінки'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='Основний опис служби'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_intro_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Основний опис служби'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Додатковий текст'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Додатковий текст'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='context_en',
            field=models.CharField(blank=True, help_text='Наприклад: із розмови з побратимами', max_length=255, null=True, verbose_name='Контекст / підпис'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='context_uk',
            field=models.CharField(blank=True, help_text='Наприклад: із розмови з побратимами', max_length=255, null=True, verbose_name='Контекст / підпис'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Цитата'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Цитата'),
        ),
    ]
