# Generated by Django 6.0.7 on 2026-09-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_serviceaward_decree_source_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='award_subtitle',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='award_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='award_subtitle_uk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='award_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='award_title_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='award_title_uk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='decree_date',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='decree_number',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='decree_source_name',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='decree_source_name_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='decree_source_name_uk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='decree_url',
        ),
    ]
