# Generated by Django 6.0.7 on 2026-09-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_servicepage_award_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='editorial_note',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='editorial_note_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='editorial_note_uk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_intro',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_intro_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_intro_uk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_text',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_text_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='service_text_uk',
        ),
    ]
