# Generated by Django 6.0.7 on 2026-09-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_servicepage_editorial_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='award_date_label',
            field=models.CharField(default='Дата указу', max_length=100, verbose_name='Підпис дати указу'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_date_label_en',
            field=models.CharField(default='Дата указу', max_length=100, null=True, verbose_name='Підпис дати указу'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_date_label_uk',
            field=models.CharField(default='Дата указу', max_length=100, null=True, verbose_name='Підпис дати указу'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_number_label',
            field=models.CharField(default='Номер', max_length=100, verbose_name='Підпис номера указу'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_number_label_en',
            field=models.CharField(default='Номер', max_length=100, null=True, verbose_name='Підпис номера указу'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_number_label_uk',
            field=models.CharField(default='Номер', max_length=100, null=True, verbose_name='Підпис номера указу'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_source_label',
            field=models.CharField(default='Джерело', max_length=100, verbose_name='Підпис джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_source_label_en',
            field=models.CharField(default='Джерело', max_length=100, null=True, verbose_name='Підпис джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='award_source_label_uk',
            field=models.CharField(default='Джерело', max_length=100, null=True, verbose_name='Підпис джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='awards_eyebrow',
            field=models.CharField(default='Нагороди', max_length=100, verbose_name='Підпис блоку нагород'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='awards_eyebrow_en',
            field=models.CharField(default='Нагороди', max_length=100, null=True, verbose_name='Підпис блоку нагород'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='awards_eyebrow_uk',
            field=models.CharField(default='Нагороди', max_length=100, null=True, verbose_name='Підпис блоку нагород'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='awards_title',
            field=models.CharField(default='Нагороди та відзнаки', max_length=255, verbose_name='Заголовок блоку нагород'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='awards_title_en',
            field=models.CharField(default='Нагороди та відзнаки', max_length=255, null=True, verbose_name='Заголовок блоку нагород'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='awards_title_uk',
            field=models.CharField(default='Нагороди та відзнаки', max_length=255, null=True, verbose_name='Заголовок блоку нагород'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='index_eyebrow',
            field=models.CharField(default='На сторінці', max_length=100, verbose_name='Підпис навігації'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='index_eyebrow_en',
            field=models.CharField(default='На сторінці', max_length=100, null=True, verbose_name='Підпис навігації'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='index_eyebrow_uk',
            field=models.CharField(default='На сторінці', max_length=100, null=True, verbose_name='Підпис навігації'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_eyebrow',
            field=models.CharField(default='Посилання', max_length=100, verbose_name='Підпис блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_eyebrow_en',
            field=models.CharField(default='Посилання', max_length=100, null=True, verbose_name='Підпис блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_eyebrow_uk',
            field=models.CharField(default='Посилання', max_length=100, null=True, verbose_name='Підпис блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_missing_date_label',
            field=models.CharField(default='Дата не вказана', max_length=100, verbose_name='Текст, якщо дата не вказана'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_missing_date_label_en',
            field=models.CharField(default='Дата не вказана', max_length=100, null=True, verbose_name='Текст, якщо дата не вказана'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_missing_date_label_uk',
            field=models.CharField(default='Дата не вказана', max_length=100, null=True, verbose_name='Текст, якщо дата не вказана'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_title',
            field=models.CharField(default='Матеріали та джерела', max_length=255, verbose_name='Заголовок блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_title_en',
            field=models.CharField(default='Матеріали та джерела', max_length=255, null=True, verbose_name='Заголовок блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_title_uk',
            field=models.CharField(default='Матеріали та джерела', max_length=255, null=True, verbose_name='Заголовок блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quote_more_label',
            field=models.CharField(default='Дивитись більше', max_length=100, verbose_name='Текст кнопки розгортання цитати'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quote_more_label_en',
            field=models.CharField(default='Дивитись більше', max_length=100, null=True, verbose_name='Текст кнопки розгортання цитати'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quote_more_label_uk',
            field=models.CharField(default='Дивитись більше', max_length=100, null=True, verbose_name='Текст кнопки розгортання цитати'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_eyebrow',
            field=models.CharField(default='Цитати', max_length=100, verbose_name='Підпис блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_eyebrow_en',
            field=models.CharField(default='Цитати', max_length=100, null=True, verbose_name='Підпис блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_eyebrow_uk',
            field=models.CharField(default='Цитати', max_length=100, null=True, verbose_name='Підпис блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_title',
            field=models.CharField(default='Слова, що залишилися', max_length=255, verbose_name='Заголовок блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_title_en',
            field=models.CharField(default='Слова, що залишилися', max_length=255, null=True, verbose_name='Заголовок блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_title_uk',
            field=models.CharField(default='Слова, що залишилися', max_length=255, null=True, verbose_name='Заголовок блоку цитат'),
        ),
    ]
