# Generated by Django 6.0.7 on 2026-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_servicepage_award_date_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='links_description',
            field=models.TextField(blank=True, default='Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.', verbose_name='Опис блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_description_en',
            field=models.TextField(blank=True, default='Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.', null=True, verbose_name='Опис блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_description_uk',
            field=models.TextField(blank=True, default='Перевірені посилання на публікації, офіційні документи й матеріали вшанування — без копіювання повних текстів.', null=True, verbose_name='Опис блоку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_empty_text',
            field=models.TextField(blank=True, default='Перевірені публікації та офіційні джерела з’являться тут пізніше.', verbose_name='Текст, якщо посилань немає'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_empty_text_en',
            field=models.TextField(blank=True, default='Перевірені публікації та офіційні джерела з’являться тут пізніше.', null=True, verbose_name='Текст, якщо посилань немає'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_empty_text_uk',
            field=models.TextField(blank=True, default='Перевірені публікації та офіційні джерела з’являться тут пізніше.', null=True, verbose_name='Текст, якщо посилань немає'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_empty_title',
            field=models.CharField(default='Матеріалів поки немає', max_length=255, verbose_name='Заголовок, якщо посилань немає'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_empty_title_en',
            field=models.CharField(default='Матеріалів поки немає', max_length=255, null=True, verbose_name='Заголовок, якщо посилань немає'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_empty_title_uk',
            field=models.CharField(default='Матеріалів поки немає', max_length=255, null=True, verbose_name='Заголовок, якщо посилань немає'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_nav_label',
            field=models.CharField(default='Посилання', max_length=100, verbose_name='Назва в навігації'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_nav_label_en',
            field=models.CharField(default='Посилання', max_length=100, null=True, verbose_name='Назва в навігації'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_nav_label_uk',
            field=models.CharField(default='Посилання', max_length=100, null=True, verbose_name='Назва в навігації'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_verification_note',
            field=models.TextField(blank=True, default='Перевірка посилань рекомендована 1–2 рази на рік.', verbose_name='Примітка про перевірку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_verification_note_en',
            field=models.TextField(blank=True, default='Перевірка посилань рекомендована 1–2 рази на рік.', null=True, verbose_name='Примітка про перевірку посилань'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_verification_note_uk',
            field=models.TextField(blank=True, default='Перевірка посилань рекомендована 1–2 рази на рік.', null=True, verbose_name='Примітка про перевірку посилань'),
        ),
    ]
