# Generated by Django 6.0.7 on 2026-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_portrait_empty_label',
            field=models.CharField(default='Головне фото ще не додано', max_length=150, verbose_name='Текст, якщо головне фото не додано'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_portrait_empty_label_en',
            field=models.CharField(default='Головне фото ще не додано', max_length=150, null=True, verbose_name='Текст, якщо головне фото не додано'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_portrait_empty_label_uk',
            field=models.CharField(default='Головне фото ще не додано', max_length=150, null=True, verbose_name='Текст, якщо головне фото не додано'),
        ),
    ]
