# Generated by Django 6.0.7 on 2026-09-10 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_preview_focus'),
        ('pages', '0010_lifepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifepage',
            name='childhood_photo',
            field=models.ForeignKey(blank=True, help_text='Оберіть опубліковане фото, яке буде показано в картці «Дитинство».', limit_choices_to={'is_published': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Фото для картки «Дитинство»'),
        ),
        migrations.AddField(
            model_name='lifepage',
            name='family_photo',
            field=models.ForeignKey(blank=True, help_text='Оберіть опубліковане фото, яке буде показано в картці «Родина».', limit_choices_to={'is_published': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Фото для картки «Родина»'),
        ),
        migrations.AddField(
            model_name='lifepage',
            name='study_photo',
            field=models.ForeignKey(blank=True, help_text='Оберіть опубліковане фото, яке буде показано в картці «Навчання».', limit_choices_to={'is_published': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Фото для картки «Навчання»'),
        ),
    ]
