# Generated by Django 6.0.7 on 2026-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_lifepage_childhood_photo_lifepage_family_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Фотоархів', max_length=200, verbose_name='Текст над заголовком')),
                ('hero_eyebrow_uk', models.CharField(default='Фотоархів', max_length=200, null=True, verbose_name='Текст над заголовком')),
                ('hero_eyebrow_en', models.CharField(default='Фотоархів', max_length=200, null=True, verbose_name='Текст над заголовком')),
                ('hero_description', models.TextField(default='Основний архів світлин, згрупований за періодами життя.', verbose_name='Опис першого екрану')),
                ('hero_description_uk', models.TextField(default='Основний архів світлин, згрупований за періодами життя.', null=True, verbose_name='Опис першого екрану')),
                ('hero_description_en', models.TextField(default='Основний архів світлин, згрупований за періодами життя.', null=True, verbose_name='Опис першого екрану')),
                ('verification_note', models.TextField(blank=True, default='Кожне фото публікується лише після перевірки.', verbose_name='Примітка про перевірку фото')),
                ('verification_note_uk', models.TextField(blank=True, default='Кожне фото публікується лише після перевірки.', null=True, verbose_name='Примітка про перевірку фото')),
                ('verification_note_en', models.TextField(blank=True, default='Кожне фото публікується лише після перевірки.', null=True, verbose_name='Примітка про перевірку фото')),
                ('show_more_label', models.CharField(default='Показати більше', max_length=100, verbose_name='Текст кнопки завантаження наступних фото')),
                ('show_more_label_uk', models.CharField(default='Показати більше', max_length=100, null=True, verbose_name='Текст кнопки завантаження наступних фото')),
                ('show_more_label_en', models.CharField(default='Показати більше', max_length=100, null=True, verbose_name='Текст кнопки завантаження наступних фото')),
                ('category_empty_text', models.CharField(default='У цій категорії поки немає фотографій.', max_length=250, verbose_name='Текст, якщо у вибраній категорії немає фото')),
                ('category_empty_text_uk', models.CharField(default='У цій категорії поки немає фотографій.', max_length=250, null=True, verbose_name='Текст, якщо у вибраній категорії немає фото')),
                ('category_empty_text_en', models.CharField(default='У цій категорії поки немає фотографій.', max_length=250, null=True, verbose_name='Текст, якщо у вибраній категорії немає фото')),
                ('empty_title', models.CharField(default='Фотоархів ще наповнюється', max_length=200, verbose_name='Заголовок, якщо фотоархів порожній')),
                ('empty_title_uk', models.CharField(default='Фотоархів ще наповнюється', max_length=200, null=True, verbose_name='Заголовок, якщо фотоархів порожній')),
                ('empty_title_en', models.CharField(default='Фотоархів ще наповнюється', max_length=200, null=True, verbose_name='Заголовок, якщо фотоархів порожній')),
                ('empty_text', models.TextField(default='Перевірені родиною фотографії з’являться тут після публікації.', verbose_name='Текст, якщо фотоархів порожній')),
                ('empty_text_uk', models.TextField(default='Перевірені родиною фотографії з’являться тут після публікації.', null=True, verbose_name='Текст, якщо фотоархів порожній')),
                ('empty_text_en', models.TextField(default='Перевірені родиною фотографії з’являться тут після публікації.', null=True, verbose_name='Текст, якщо фотоархів порожній')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
