# Generated by Django 6.0.7 on 2026-09-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_seed_photopage_from_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Архівні записи', max_length=100, verbose_name='Текст над заголовком')),
                ('hero_eyebrow_uk', models.CharField(default='Архівні записи', max_length=100, null=True, verbose_name='Текст над заголовком')),
                ('hero_eyebrow_en', models.CharField(default='Архівні записи', max_length=100, null=True, verbose_name='Текст над заголовком')),
                ('hero_description', models.TextField(default='Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.', verbose_name='Опис першого екрану')),
                ('hero_description_uk', models.TextField(default='Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.', null=True, verbose_name='Опис першого екрану')),
                ('hero_description_en', models.TextField(default='Сімейні записи, інтерв’ю, матеріали зі служби та відео вшанування.', null=True, verbose_name='Опис першого екрану')),
                ('featured_label', models.CharField(default='Рекомендоване відео', max_length=150, verbose_name='Підпис рекомендованого відео')),
                ('featured_label_uk', models.CharField(default='Рекомендоване відео', max_length=150, null=True, verbose_name='Підпис рекомендованого відео')),
                ('featured_label_en', models.CharField(default='Рекомендоване відео', max_length=150, null=True, verbose_name='Підпис рекомендованого відео')),
                ('transcript_label', models.CharField(default='Текстовий опис відео', max_length=150, verbose_name='Заголовок розшифровки відео')),
                ('transcript_label_uk', models.CharField(default='Текстовий опис відео', max_length=150, null=True, verbose_name='Заголовок розшифровки відео')),
                ('transcript_label_en', models.CharField(default='Текстовий опис відео', max_length=150, null=True, verbose_name='Заголовок розшифровки відео')),
                ('archive_eyebrow', models.CharField(default='Усі записи', max_length=100, verbose_name='Підпис блоку відеоархіву')),
                ('archive_eyebrow_uk', models.CharField(default='Усі записи', max_length=100, null=True, verbose_name='Підпис блоку відеоархіву')),
                ('archive_eyebrow_en', models.CharField(default='Усі записи', max_length=100, null=True, verbose_name='Підпис блоку відеоархіву')),
                ('archive_title', models.CharField(default='Відеоархів', max_length=200, verbose_name='Заголовок відеоархіву')),
                ('archive_title_uk', models.CharField(default='Відеоархів', max_length=200, null=True, verbose_name='Заголовок відеоархіву')),
                ('archive_title_en', models.CharField(default='Відеоархів', max_length=200, null=True, verbose_name='Заголовок відеоархіву')),
                ('archive_note', models.TextField(default='Усі матеріали додаються та публікуються тільки через адміністративну панель.', verbose_name='Примітка біля відеоархіву')),
                ('archive_note_uk', models.TextField(default='Усі матеріали додаються та публікуються тільки через адміністративну панель.', null=True, verbose_name='Примітка біля відеоархіву')),
                ('archive_note_en', models.TextField(default='Усі матеріали додаються та публікуються тільки через адміністративну панель.', null=True, verbose_name='Примітка біля відеоархіву')),
                ('empty_title', models.CharField(default='Відеоархів ще наповнюється', max_length=200, verbose_name='Заголовок, якщо відеоархів порожній')),
                ('empty_title_uk', models.CharField(default='Відеоархів ще наповнюється', max_length=200, null=True, verbose_name='Заголовок, якщо відеоархів порожній')),
                ('empty_title_en', models.CharField(default='Відеоархів ще наповнюється', max_length=200, null=True, verbose_name='Заголовок, якщо відеоархів порожній')),
                ('empty_text', models.TextField(default='Перевірені відеоматеріали з’являться тут після публікації адміністратором.', verbose_name='Текст, якщо відеоархів порожній')),
                ('empty_text_uk', models.TextField(default='Перевірені відеоматеріали з’являться тут після публікації адміністратором.', null=True, verbose_name='Текст, якщо відеоархів порожній')),
                ('empty_text_en', models.TextField(default='Перевірені відеоматеріали з’являться тут після публікації адміністратором.', null=True, verbose_name='Текст, якщо відеоархів порожній')),
                ('accessibility_label', models.CharField(default='Доступність:', max_length=100, verbose_name='Заголовок примітки про доступність')),
                ('accessibility_label_uk', models.CharField(default='Доступність:', max_length=100, null=True, verbose_name='Заголовок примітки про доступність')),
                ('accessibility_label_en', models.CharField(default='Доступність:', max_length=100, null=True, verbose_name='Заголовок примітки про доступність')),
                ('accessibility_text', models.TextField(default='за можливості до відео додається текстовий опис або розшифровка.', verbose_name='Текст примітки про доступність')),
                ('accessibility_text_uk', models.TextField(default='за можливості до відео додається текстовий опис або розшифровка.', null=True, verbose_name='Текст примітки про доступність')),
                ('accessibility_text_en', models.TextField(default='за можливості до відео додається текстовий опис або розшифровка.', null=True, verbose_name='Текст примітки про доступність')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Відео',
                'verbose_name_plural': 'Відео',
            },
        ),
    ]
