# Generated by Django 6.0.7 on 2026-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_videopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='quote_jump_label',
            field=models.CharField(default='Перейти до цитат', max_length=300, verbose_name='Опис переходу до цитат'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_jump_label_en',
            field=models.CharField(default='Перейти до цитат', max_length=300, null=True, verbose_name='Опис переходу до цитат'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_jump_label_uk',
            field=models.CharField(default='Перейти до цитат', max_length=300, null=True, verbose_name='Опис переходу до цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_count_label',
            field=models.CharField(default='Джерела', max_length=300, verbose_name='Підпис кількості джерел'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_count_label_en',
            field=models.CharField(default='Джерела', max_length=300, null=True, verbose_name='Підпис кількості джерел'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='links_count_label_uk',
            field=models.CharField(default='Джерела', max_length=300, null=True, verbose_name='Підпис кількості джерел'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quote_less_label',
            field=models.CharField(default='Згорнути', max_length=300, verbose_name='Текст кнопки згортання цитати'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quote_less_label_en',
            field=models.CharField(default='Згорнути', max_length=300, null=True, verbose_name='Текст кнопки згортання цитати'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quote_less_label_uk',
            field=models.CharField(default='Згорнути', max_length=300, null=True, verbose_name='Текст кнопки згортання цитати'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_description',
            field=models.CharField(default='Слова самого Назара — з листів, розмов і записів у блокноті. Короткі цитати показані повністю, довгі — скорочені з кнопкою розгортання.', max_length=300, verbose_name='Опис блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_description_en',
            field=models.CharField(default='Слова самого Назара — з листів, розмов і записів у блокноті. Короткі цитати показані повністю, довгі — скорочені з кнопкою розгортання.', max_length=300, null=True, verbose_name='Опис блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='quotes_description_uk',
            field=models.CharField(default='Слова самого Назара — з листів, розмов і записів у блокноті. Короткі цитати показані повністю, довгі — скорочені з кнопкою розгортання.', max_length=300, null=True, verbose_name='Опис блоку цитат'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='source_open_label',
            field=models.CharField(default='Відкрити джерело', max_length=300, verbose_name='Опис відкриття джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='source_open_label_en',
            field=models.CharField(default='Відкрити джерело', max_length=300, null=True, verbose_name='Опис відкриття джерела'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='source_open_label_uk',
            field=models.CharField(default='Відкрити джерело', max_length=300, null=True, verbose_name='Опис відкриття джерела'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='text_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='text_uk',
            field=models.TextField(max_length=1500, null=True, verbose_name='Цитата'),
        ),
    ]
