# Generated by Django 6.0.7 on 2026-09-15 09:44

import apps.pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_quote_presentation_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicequote',
            name='text',
            field=models.TextField(max_length=1500, validators=[apps.pages.validators.validate_service_quote], verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='text_en',
            field=models.TextField(max_length=1500, null=True, validators=[apps.pages.validators.validate_service_quote], verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='text_uk',
            field=models.TextField(max_length=1500, null=True, validators=[apps.pages.validators.validate_service_quote], verbose_name='Цитата'),
        ),
    ]
