# Generated by Django 6.0.7 on 2026-09-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_seed_quote_labels_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='honour_title',
            field=models.CharField(blank=True, default='', help_text='Наприклад: Герой України. Якщо порожньо — плашка не показується.', max_length=200, verbose_name='Звання'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='honour_title_en',
            field=models.CharField(blank=True, default='', help_text='Наприклад: Герой України. Якщо порожньо — плашка не показується.', max_length=200, null=True, verbose_name='Звання'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='honour_title_uk',
            field=models.CharField(blank=True, default='', help_text='Наприклад: Герой України. Якщо порожньо — плашка не показується.', max_length=200, null=True, verbose_name='Звання'),
        ),
    ]
